import SwiftUI
import Warp

struct DatavizTokensView: View {
    private let tokenProvider = Warp.DatavizToken

    var body: some View {
        ScrollView(showsIndicators: false) {
            VStack (alignment: .leading) {
                    createView(for: "datafillPrimary",
                               colors: [tokenProvider.datafillPrimary])
                    createView(for: "datafillPrimaryFocus",
                               colors: [tokenProvider.datafillPrimaryFocus])
                    createView(for: "datafillSecondary",
                           colors: [tokenProvider.datafillSecondary])
                    createView(for: "datafillSecondaryFocus",
                           colors: [tokenProvider.datafillSecondaryFocus])
                    createView(for: "datafillCategory1",
                           colors: [tokenProvider.datafillCategory1])
                    createView(for: "datafillCategory1Focus",
                           colors: [tokenProvider.datafillCategory1Focus])
                    createView(for: "datafillCategory2",
                           colors: [tokenProvider.datafillCategory2])
                    createView(for: "datafillCategory2Focus",
                           colors: [tokenProvider.datafillCategory2Focus])
                    createView(for: "datafillCategory3",
                           colors: [tokenProvider.datafillCategory3])
                    createView(for: "datafillCategory3Focus",
                           colors: [tokenProvider.datafillCategory3Focus])
                    createView(for: "datafillCategory4",
                           colors: [tokenProvider.datafillCategory4])
                    createView(for: "datafillCategory4Focus",
                           colors: [tokenProvider.datafillCategory4Focus])
                    createView(for: "datafillCategory5",
                           colors: [tokenProvider.datafillCategory5])
                    createView(for: "datafillCategory5Focus",
                           colors: [tokenProvider.datafillCategory5Focus])
                    createView(for: "datafillCategory6",
                           colors: [tokenProvider.datafillCategory6])
                    createView(for: "datafillCategory6Focus",
                           colors: [tokenProvider.datafillCategory6Focus])
                    createView(for: "datafillCategory7",
                           colors: [tokenProvider.datafillCategory7])
                    createView(for: "datafillCategory7Focus",
                           colors: [tokenProvider.datafillCategory7Focus])
                    createView(for: "datafillCategory8",
                           colors: [tokenProvider.datafillCategory8])
                    createView(for: "datafillCategory8Focus",
                           colors: [tokenProvider.datafillCategory8Focus])
                    createView(for: "datafillPositive",
                           colors: [tokenProvider.datafillPositive])
                    createView(for: "datafillPositiveFocus",
                           colors: [tokenProvider.datafillPositiveFocus])
                    createView(for: "datafillWarning",
                           colors: [tokenProvider.datafillWarning])
                    createView(for: "datafillWarningFocus",
                           colors: [tokenProvider.datafillWarningFocus])
                    createView(for: "datafillNegative",
                           colors: [tokenProvider.datafillNegative])
                    createView(for: "datafillNegativeFocus",
                           colors: [tokenProvider.datafillNegativeFocus])
                    createView(for: "datafillNeutral",
                           colors: [tokenProvider.datafillNeutral])
                    createView(for: "datafillNeutralFocus",
                           colors: [tokenProvider.datafillNeutralFocus])
                    createView(for: "datafillPrimarySubtle",
                           colors: [tokenProvider.datafillPrimarySubtle])
                    createView(for: "datafillPrimarySubtleFocus",
                           colors: [tokenProvider.datafillPrimarySubtleFocus])
                    createView(for: "datafillSecondarySubtle",
                           colors: [tokenProvider.datafillSecondarySubtle])
                    createView(for: "datafillSecondarySubtleFocus",
                           colors: [tokenProvider.datafillSecondarySubtleFocus])
                    createView(for: "datafillCategory1Subtle",
                           colors: [tokenProvider.datafillCategory1Subtle])
                    createView(for: "datafillCategory1SubtleFocus",
                           colors: [tokenProvider.datafillCategory1SubtleFocus])
                    createView(for: "datafillCategory2Subtle",
                           colors: [tokenProvider.datafillCategory2Subtle])
                    createView(for: "datafillCategory2SubtleFocus",
                           colors: [tokenProvider.datafillCategory2SubtleFocus])
                    createView(for: "datafillCategory3Subtle",
                           colors: [tokenProvider.datafillCategory3Subtle])
                    createView(for: "datafillCategory3SubtleFocus",
                           colors: [tokenProvider.datafillCategory3SubtleFocus])
                    createView(for: "datafillCategory4Subtle",
                           colors: [tokenProvider.datafillCategory4Subtle])
                    createView(for: "datafillCategory4SubtleFocus",
                           colors: [tokenProvider.datafillCategory4SubtleFocus])
                    createView(for: "datafillCategory5Subtle",
                           colors: [tokenProvider.datafillCategory5Subtle])
                    createView(for: "datafillCategory5SubtleFocus",
                           colors: [tokenProvider.datafillCategory5SubtleFocus])
                    createView(for: "datafillCategory6Subtle",
                           colors: [tokenProvider.datafillCategory6Subtle])
                    createView(for: "datafillCategory6SubtleFocus",
                           colors: [tokenProvider.datafillCategory6SubtleFocus])
                    createView(for: "datafillCategory7Subtle",
                           colors: [tokenProvider.datafillCategory7Subtle])
                    createView(for: "datafillCategory7SubtleFocus",
                           colors: [tokenProvider.datafillCategory7SubtleFocus])
                    createView(for: "datafillCategory8Subtle",
                           colors: [tokenProvider.datafillCategory8Subtle])
                    createView(for: "datafillCategory8SubtleFocus",
                           colors: [tokenProvider.datafillCategory8SubtleFocus])
                    createView(for: "datafillPositiveSubtle",
                           colors: [tokenProvider.datafillPositiveSubtle])
                    createView(for: "datafillPositiveSubtleFocus",
                           colors: [tokenProvider.datafillPositiveSubtleFocus])
                    createView(for: "datafillWarningSubtle",
                           colors: [tokenProvider.datafillWarningSubtle])
                    createView(for: "datafillWarningSubtleFocus",
                           colors: [tokenProvider.datafillWarningSubtleFocus])
                    createView(for: "datafillNegativeSubtle",
                           colors: [tokenProvider.datafillNegativeSubtle])
                    createView(for: "datafillNegativeSubtleFocus",
                           colors: [tokenProvider.datafillNegativeSubtleFocus])
                    createView(for: "datafillNeutralSubtle",
                           colors: [tokenProvider.datafillNeutralSubtle])
                    createView(for: "datafillNeutralSubtleFocus",
                           colors: [tokenProvider.datafillNeutralSubtleFocus])
                    createView(for: "datalinePrimary",
                           colors: [tokenProvider.datalinePrimary])
                    createView(for: "datalinePrimaryFocus",
                           colors: [tokenProvider.datalinePrimaryFocus])
                    createView(for: "datalineSecondary",
                           colors: [tokenProvider.datalineSecondary])
                    createView(for: "datalineSecondaryFocus",
                           colors: [tokenProvider.datalineSecondaryFocus])
                    createView(for: "datalineCategory1",
                           colors: [tokenProvider.datalineCategory1])
                    createView(for: "datalineCategory1Focus",
                           colors: [tokenProvider.datalineCategory1Focus])
                    createView(for: "datalineCategory2",
                           colors: [tokenProvider.datalineCategory2])
                    createView(for: "datalineCategory2Focus",
                           colors: [tokenProvider.datalineCategory2Focus])
                    createView(for: "datalineCategory3",
                           colors: [tokenProvider.datalineCategory3])
                    createView(for: "datalineCategory3Focus",
                           colors: [tokenProvider.datalineCategory3Focus])
                    createView(for: "datalineCategory4",
                           colors: [tokenProvider.datalineCategory4])
                    createView(for: "datalineCategory4Focus",
                           colors: [tokenProvider.datalineCategory4Focus])
                    createView(for: "datalineCategory5",
                           colors: [tokenProvider.datalineCategory5])
                    createView(for: "datalineCategory5Focus",
                           colors: [tokenProvider.datalineCategory5Focus])
                    createView(for: "datalineCategory6",
                           colors: [tokenProvider.datalineCategory6])
                    createView(for: "datalineCategory6Focus",
                           colors: [tokenProvider.datalineCategory6Focus])
                    createView(for: "datalineCategory7",
                           colors: [tokenProvider.datalineCategory7])
                    createView(for: "datalineCategory7Focus",
                           colors: [tokenProvider.datalineCategory7Focus])
                    createView(for: "datalineCategory8",
                           colors: [tokenProvider.datalineCategory8])
                    createView(for: "datalineCategory8Focus",
                           colors: [tokenProvider.datalineCategory8Focus])
                    createView(for: "datalinePositive",
                           colors: [tokenProvider.datalinePositive])
                    createView(for: "datalinePositiveFocus",
                           colors: [tokenProvider.datalinePositiveFocus])
                    createView(for: "datalineWarning",
                           colors: [tokenProvider.datalineWarning])
                    createView(for: "datalineWarningFocus",
                           colors: [tokenProvider.datalineWarningFocus])
                    createView(for: "datalineNegative",
                           colors: [tokenProvider.datalineNegative])
                    createView(for: "datalineNegativeFocus",
                           colors: [tokenProvider.datalineNegativeFocus])
                    createView(for: "datalineNeutral",
                           colors: [tokenProvider.datalineNeutral])
                    createView(for: "datalineNeutralFocus",
                           colors: [tokenProvider.datalineNeutralFocus])
                    createView(for: "databorderPrimary",
                           colors: [tokenProvider.databorderPrimary])
                    createView(for: "databorderPrimaryFocus",
                           colors: [tokenProvider.databorderPrimaryFocus])
                    createView(for: "databorderSecondary",
                           colors: [tokenProvider.databorderSecondary])
                    createView(for: "databorderSecondaryFocus",
                           colors: [tokenProvider.databorderSecondaryFocus])
                    createView(for: "databorderCategory1",
                           colors: [tokenProvider.databorderCategory1])
                    createView(for: "databorderCategory1Focus",
                           colors: [tokenProvider.databorderCategory1Focus])
                    createView(for: "databorderCategory2",
                           colors: [tokenProvider.databorderCategory2])
                    createView(for: "databorderCategory2Focus",
                           colors: [tokenProvider.databorderCategory2Focus])
                    createView(for: "databorderCategory3",
                           colors: [tokenProvider.databorderCategory3])
                    createView(for: "databorderCategory3Focus",
                           colors: [tokenProvider.databorderCategory3Focus])
                    createView(for: "databorderCategory4",
                           colors: [tokenProvider.databorderCategory4])
                    createView(for: "databorderCategory4Focus",
                           colors: [tokenProvider.databorderCategory4Focus])
                    createView(for: "databorderCategory5",
                           colors: [tokenProvider.databorderCategory5])
                    createView(for: "databorderCategory5Focus",
                           colors: [tokenProvider.databorderCategory5Focus])
                    createView(for: "databorderCategory6",
                           colors: [tokenProvider.databorderCategory6])
                    createView(for: "databorderCategory6Focus",
                           colors: [tokenProvider.databorderCategory6Focus])
                    createView(for: "databorderCategory7",
                           colors: [tokenProvider.databorderCategory7])
                    createView(for: "databorderCategory7Focus",
                           colors: [tokenProvider.databorderCategory7Focus])
                    createView(for: "databorderCategory8",
                           colors: [tokenProvider.databorderCategory8])
                    createView(for: "databorderCategory8Focus",
                           colors: [tokenProvider.databorderCategory8Focus])
                    createView(for: "databorderPositive",
                           colors: [tokenProvider.databorderPositive])
                    createView(for: "databorderPositiveFocus",
                           colors: [tokenProvider.databorderPositiveFocus])
                    createView(for: "databorderWarning",
                           colors: [tokenProvider.databorderWarning])
                    createView(for: "databorderWarningFocus",
                           colors: [tokenProvider.databorderWarningFocus])
                    createView(for: "databorderNegative",
                           colors: [tokenProvider.databorderNegative])
                    createView(for: "databorderNegativeFocus",
                           colors: [tokenProvider.databorderNegativeFocus])
                    createView(for: "databorderNeutral",
                           colors: [tokenProvider.databorderNeutral])
                    createView(for: "databorderNeutralFocus",
                           colors: [tokenProvider.databorderNeutralFocus])
                    createView(for: "datatextPrimary",
                           colors: [tokenProvider.datatextPrimary])
                    createView(for: "datatextPrimaryFocus",
                           colors: [tokenProvider.datatextPrimaryFocus])
                    createView(for: "datatextSecondary",
                           colors: [tokenProvider.datatextSecondary])
                    createView(for: "datatextSecondaryFocus",
                           colors: [tokenProvider.datatextSecondaryFocus])
                    createView(for: "datatextCategorical1",
                           colors: [tokenProvider.datatextCategorical1])
                    createView(for: "datatextCategorical1Focus",
                           colors: [tokenProvider.datatextCategorical1Focus])
                    createView(for: "datatextCategorical2",
                           colors: [tokenProvider.datatextCategorical2])
                    createView(for: "datatextCategorical2Focus",
                           colors: [tokenProvider.datatextCategorical2Focus])
                    createView(for: "datatextCategorical3",
                           colors: [tokenProvider.datatextCategorical3])
                    createView(for: "datatextCategorical3Focus",
                           colors: [tokenProvider.datatextCategorical3Focus])
                    createView(for: "datatextCategorical4",
                           colors: [tokenProvider.datatextCategorical4])
                    createView(for: "datatextCategorical4Focus",
                           colors: [tokenProvider.datatextCategorical4Focus])
                    createView(for: "datatextCategorical5",
                           colors: [tokenProvider.datatextCategorical5])
                    createView(for: "datatextCategorical5Focus",
                           colors: [tokenProvider.datatextCategorical5Focus])
                    createView(for: "datatextCategorical6",
                           colors: [tokenProvider.datatextCategorical6])
                    createView(for: "datatextCategorical6Focus",
                           colors: [tokenProvider.datatextCategorical6Focus])
                    createView(for: "datatextCategorical7",
                           colors: [tokenProvider.datatextCategorical7])
                    createView(for: "datatextCategorical7Focus",
                           colors: [tokenProvider.datatextCategorical7Focus])
                    createView(for: "datatextCategorical8",
                           colors: [tokenProvider.datatextCategorical8])
                    createView(for: "datatextCategorical8Focus",
                           colors: [tokenProvider.datatextCategorical8Focus])
                    createView(for: "datatextPositive",
                           colors: [tokenProvider.datatextPositive])
                    createView(for: "datatextPositiveFocus",
                           colors: [tokenProvider.datatextPositiveFocus])
                    createView(for: "datatextWarning",
                           colors: [tokenProvider.datatextWarning])
                    createView(for: "datatextWarningFocus",
                           colors: [tokenProvider.datatextWarningFocus])
                    createView(for: "datatextNegative",
                           colors: [tokenProvider.datatextNegative])
                    createView(for: "datatextNegativeFocus",
                           colors: [tokenProvider.datatextNegativeFocus])
                    createView(for: "datatextNeutral",
                           colors: [tokenProvider.datatextNeutral])
                    createView(for: "datatextNeutralFocus",
                           colors: [tokenProvider.datatextNeutralFocus])
                    createView(for: "dataiconPrimary",
                           colors: [tokenProvider.dataiconPrimary])
                    createView(for: "dataiconPrimaryFocus",
                           colors: [tokenProvider.dataiconPrimaryFocus])
                    createView(for: "dataiconSecondary",
                           colors: [tokenProvider.dataiconSecondary])
                    createView(for: "dataiconSecondaryFocus",
                           colors: [tokenProvider.dataiconSecondaryFocus])
                    createView(for: "dataiconCategorical1",
                           colors: [tokenProvider.dataiconCategorical1])
                    createView(for: "dataiconCategorical1Focus",
                           colors: [tokenProvider.dataiconCategorical1Focus])
                    createView(for: "dataiconCategorical2",
                           colors: [tokenProvider.dataiconCategorical2])
                    createView(for: "dataiconCategorical2Focus",
                           colors: [tokenProvider.dataiconCategorical2Focus])
                    createView(for: "dataiconCategorical3",
                           colors: [tokenProvider.dataiconCategorical3])
                    createView(for: "dataiconCategorical3Focus",
                           colors: [tokenProvider.dataiconCategorical3Focus])
                    createView(for: "dataiconCategorical4",
                           colors: [tokenProvider.dataiconCategorical4])
                    createView(for: "dataiconCategorical4Focus",
                           colors: [tokenProvider.dataiconCategorical4Focus])
                    createView(for: "dataiconCategorical5",
                           colors: [tokenProvider.dataiconCategorical5])
                    createView(for: "dataiconCategorical5Focus",
                           colors: [tokenProvider.dataiconCategorical5Focus])
                    createView(for: "dataiconCategorical6",
                           colors: [tokenProvider.dataiconCategorical6])
                    createView(for: "dataiconCategorical6Focus",
                           colors: [tokenProvider.dataiconCategorical6Focus])
                    createView(for: "dataiconCategorical7",
                           colors: [tokenProvider.dataiconCategorical7])
                    createView(for: "dataiconCategorical7Focus",
                           colors: [tokenProvider.dataiconCategorical7Focus])
                    createView(for: "dataiconCategorical8",
                           colors: [tokenProvider.dataiconCategorical8])
                    createView(for: "dataiconCategorical8Focus",
                           colors: [tokenProvider.dataiconCategorical8Focus])
                    createView(for: "dataiconPositive",
                           colors: [tokenProvider.dataiconPositive])
                    createView(for: "dataiconPositiveFocus",
                           colors: [tokenProvider.dataiconPositiveFocus])
                    createView(for: "dataiconWarning",
                           colors: [tokenProvider.dataiconWarning])
                    createView(for: "dataiconWarningFocus",
                           colors: [tokenProvider.dataiconWarningFocus])
                    createView(for: "dataiconNegative",
                           colors: [tokenProvider.dataiconNegative])
                    createView(for: "dataiconNegativeFocus",
                           colors: [tokenProvider.dataiconNegativeFocus])
                    createView(for: "dataiconNeutral",
                           colors: [tokenProvider.dataiconNeutral])
                    createView(for: "dataiconNeutralFocus",
                           colors: [tokenProvider.dataiconNeutralFocus])
            }
            .padding(.horizontal)
            .navigationTitle("DatavizTokens")
            .navigationBarTitleDisplayMode(.inline)
        }
    }

    private func createView(for colorGroup: String, colors: [Color]) -> some View {
        return GroupBox(
            content: {
                HStack(spacing: 1) {
                    ForEach(colors, id: \.self) { color in
                        Rectangle()
                            .foregroundColor(color)
                            .frame(height: 25)
                    }
                }
            }, label: {
                Text(colorGroup)
            }
        )
    }
}

#Preview {
    DatavizTokensView()
}
