import SwiftUI

extension Warp {
    /// Icon set used across Warp components, loaded from the asset catalog in the framework.
    ///
    /// Provides both SwiftUI `Image` and UIKit `UIImage` representations for each icon.
    public enum Icon: String, CaseIterable {
        case ActiveAds
        case Ads
        case AirCon
        case AllWheelDrive
        case AnimalPaw
        case Archway
        case ArrowDown
        case ArrowLeft
        case ArrowRight
        case ArrowUp
        case Attachment
        case Automatic
        case BackWheelDrive
        case Bag
        case Bank
        case BankIdNo
        case BatteryEmpty
        case BatteryFull
        case BatteryHalfFull
        case Beach
        case Bell
        case BellFilled
        case Bin
        case Block
        case BoatLength
        case Bolt
        case Bookmark
        case Browser
        case BrowserVerified
        case Building
        case BuildingPlot
        case Bulb
        case Burger
        case Bus
        case CabinHut
        case Calculator
        case Calendar
        case Camera
        case Cancel
        case Car
        case CarKey
        case CarService
        case Charger
        case Charter
        case ChatRequest
        case ChatSupport
        case Check
        case Checklist
        case CheckShield
        case ChevronDoubleLeft
        case ChevronDoubleRight
        case ChevronDown
        case ChevronLeft
        case ChevronRight
        case ChevronUp
        case CirclePlus
        case CirclePlusFilled
        case CircleUser
        case CircleUserFilled
        case Clock
        case Close
        case Cog
        case ColorPalette
        case CottagePlot
        case CreditCard
        case Cursor
        case Delivery
        case Diner
        case Discount
        case Dislike
        case Door
        case Dots
        case DoubleBed
        case Download
        case Drawer
        case Drink
        case Edit
        case Energy
        case Engine
        case EngineBelt
        case Error
        case Exchange
        case Expand
        case EyeOff
        case EyeOn
        case Facebook
        case Farm
        case Feedback
        case FileAdd
        case Filter
        case Fireplace
        case Fishing
        case Fitness
        case FrontWheelDrive
        case GasDiesel
        case GasFuel
        case GasHybrid
        case GraphLine
        case GraphPie
        case Grid
        case Grill
        case Headset
        case Heart
        case HeartRate
        case Hiking
        case History
        case House
        case HouseBed
        case HouseCabin
        case HouseFilled
        case HouseModern
        case HousePerson
        case Image
        case Info
        case Instagram
        case Keys
        case Krone
        case Lamp
        case Laundry
        case Layers
        case Leaf
        case Lift
        case Like
        case Link
        case LinkExternal
        case ListSort
        case LockShield
        case Logout
        case Mail
        case Mailbox
        case Manual
        case Map
        case Measure
        case Message
        case Messages
        case MessagesFilled
        case Minus
        case Mixer
        case Money
        case Mountain
        case NewAd
        case NorwegianMotor
        case NoSmoking
        case OfficeDesk
        case Organize
        case Parking
        case Phone
        case PhoneScratched
        case PhoneUsed
        case PictureStack
        case PinMarker
        case PinRound
        case PlaneTicket
        case Play
        case Playhouse
        case Plots
        case Plus
        case ProductBlink
        case ProductBump
        case ProductCarousel
        case ProductHighlightListing
        case ProductNabolagsprofil
        case ProductNoAds
        case ProductStarred
        case ProductTop
        case Propeller
        case Question
        case Refresh
        case RoomService
        case Sailing
        case Sauna
        case ScrollUp
        case Search
        case SearchFavorites
        case Seat
        case Send
        case Service
        case Share
        case Shipping
        case Shoes
        case ShoppingCart
        case Shower
        case Skyscraper
        case SmileyGood
        case SmileyHappy
        case SmileyNeutral
        case SmileySad
        case Sorting
        case Spa
        case Speedometer
        case Stairs
        case StarCheck
        case StarEmpty
        case StarFull
        case StarHalf
        case Store
        case Stove
        case Success
        case Suitcase
        case Support
        case Swimming
        case Tag
        case TaskList
        case TextBold
        case TextItalic
        case TextStrikethrough
        case TextUnderline
        case Theater
        case ThreeSixty
        case TownHouse
        case TV
        case Twitter
        case Up
        case Upload
        case User
        case UserGroup
        case Users
        case UserWoman
        case Vacuum
        case Verification
        case Wallet
        case Warning
        case Warranty
        case Wheelchair
        case Wifi
        case Woods
        case Youtube
        
        /// Returns a SwiftUI `Image` for the corresponding icon, loaded from the asset catalog.
        ///
        /// - Returns: A SwiftUI `Image` object corresponding to the icon.
        public var image: Image {
            SwiftUI.Image(rawValue, bundle: .module) // Load from framework's asset catalog
        }
        
        /// Returns a `UIImage` for the corresponding icon, loaded from the asset catalog.
        ///
        /// - Returns: A `UIImage` object corresponding to the icon.
        public var uiImage: UIImage? {
            UIImage(named: rawValue, in: .module, compatibleWith: nil) // Load from framework's asset catalog
        }
    }
}
