project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_url_env: CROWDIN_BASE_URL
base_path: .
preserve_hierarchy: true
skip_untranslated_files: false
files:
  [
    {
      "source": "Sources/Resources/Localizable.xcstrings",
      "translation": "Sources/Resources/Localizable.xcstrings",
      "multilingual": true
    }
  ]