import Foundation

extension Warp {
    enum Strings: String {
        case iconActiveAds = "icon.title.activeAds"
        case iconAds = "icon.title.ads"
        case iconAirCon = "icon.title.airCon"
        case iconAllWheelDrive = "icon.title.allWheelDrive"
        case iconAnimalPaw = "icon.title.animalPaw"
        case iconArchway = "icon.title.archway"
        case iconArrowDown = "icon.title.arrowDown"
        case iconArrowLeft = "icon.title.arrowLeft"
        case iconArrowRight = "icon.title.arrowRight"
        case iconArrowUp = "icon.title.arrowUp"
        case iconPaperclip = "icon.title.paperclip"
        case iconGearAutomatic = "icon.title.gearAutomatic"
        case iconAwardMedal = "icon.title.awardMedal"
        case iconBackWheelDrive = "icon.title.backWheelDrive"
        case iconBag = "icon.title.bag"
        case iconBank = "icon.title.bank"
        case iconBankIdNo = "icon.title.bankIdNo"
        case iconBatteryEmpty = "icon.title.batteryEmpty"
        case iconBatteryFull = "icon.title.batteryFull"
        case iconBatteryHalfFull = "icon.title.batteryHalfFull"
        case iconBeach = "icon.title.beach"
        case iconBell = "icon.title.bell"
        case iconBellFilled = "icon.title.bellFilled"
        case iconBin = "icon.title.bin"
        case iconBlock = "icon.title.block"
        case iconBoat = "icon.title.boat"
        case iconBolt = "icon.title.bolt"
        case iconBookmark = "icon.title.bookmark"
        case iconBrowser = "icon.title.browser"
        case iconBrowserVerified = "icon.title.browserVerified"
        case iconBuilding = "icon.title.building"
        case iconBuildingPlot = "icon.title.buildingPlot"
        case iconBulb = "icon.title.bulb"
        case iconBurger = "icon.title.burger"
        case iconBus = "icon.title.bus"
        case iconCabinHut = "icon.title.cabinHut"
        case iconCalculator = "icon.title.calculator"
        case iconCalendar = "icon.title.calendar"
        case iconCamera = "icon.title.camera"
        case iconCancel = "icon.title.cancel"
        case iconCar = "icon.title.car"
        case iconCarLeft = "icon.title.carLeft"
        case iconCarRight = "icon.title.carRight"
        case iconCharger = "icon.title.charger"
        case iconCharter = "icon.title.charter"
        case iconChatSupport = "icon.title.chatSupport"
        case iconCheck = "icon.title.check"
        case iconChecklist = "icon.title.checklist"
        case iconCheckShield = "icon.title.checkShield"
        case iconChevronDoubleLeft = "icon.title.chevronDoubleLeft"
        case iconChevronDoubleRight = "icon.title.chevronDoubleRight"
        case iconChevronDown = "icon.title.chevronDown"
        case iconChevronLeft = "icon.title.chevronLeft"
        case iconChevronRight = "icon.title.chevronRight"
        case iconChevronUp = "icon.title.chevronUp"
        case iconCirclePlus = "icon.title.circlePlus"
        case iconCirclePlusFilled = "icon.title.circlePlusFilled"
        case iconCircleUser = "icon.title.circleUser"
        case iconCircleUserFilled = "icon.title.circleUserFilled"
        case iconClock = "icon.title.clock"
        case iconClose = "icon.title.close"
        case iconCog = "icon.title.cog"
        case iconCopy = "icon.title.copy"
        case iconColorPalette = "icon.title.colorPalette"
        case iconCreditCard = "icon.title.creditCard"
        case iconCursor = "icon.title.cursor"
        case iconDelivery = "icon.title.delivery"
        case iconDiner = "icon.title.diner"
        case iconDiscount = "icon.title.discount"
        case iconDislike = "icon.title.dislike"
        case iconDoor = "icon.title.door"
        case iconDots = "icon.title.dots"
        case iconDotsVertical = "icon.title.dotsVertical"
        case iconDoubleBed = "icon.title.doubleBed"
        case iconDownload = "icon.title.download"
        case iconDragDots = "icon.title.dragDots"
        case iconDrawer = "icon.title.drawer"
        case iconDrink = "icon.title.drink"
        case iconEdit = "icon.title.edit"
        case iconEnergy = "icon.title.energy"
        case iconEngine = "icon.title.engine"
        case iconEngineBelt = "icon.title.engineBelt"
        case iconError = "icon.title.error"
        case iconExchange = "icon.title.exchange"
        case iconExpand = "icon.title.expand"
        case iconEyeOff = "icon.title.eyeOff"
        case iconEyeOn = "icon.title.eyeOn"
        case iconFacebook = "icon.title.facebook"
        case iconFarm = "icon.title.farm"
        case iconFileAdd = "icon.title.fileAdd"
        case iconFilter = "icon.title.filter"
        case iconFireplace = "icon.title.fireplace"
        case iconFishing = "icon.title.fishing"
        case iconDumbbell = "icon.title.dumbbell"
        case iconFrontWheelDrive = "icon.title.frontWheelDrive"
        case iconGasDiesel = "icon.title.gasDiesel"
        case iconGasFuel = "icon.title.gasFuel"
        case iconGasHybrid = "icon.title.gasHybrid"
        case iconGraphLine = "icon.title.graphLine"
        case iconGraphPie = "icon.title.graphPie"
        case iconGrid = "icon.title.grid"
        case iconGrill = "icon.title.grill"
        case iconHeadset = "icon.title.headset"
        case iconHeart = "icon.title.heart"
        case iconHeartRate = "icon.title.heartRate"
        case iconHiking = "icon.title.hiking"
        case iconHistory = "icon.title.history"
        case iconHouse = "icon.title.house"
        case iconHouseBed = "icon.title.houseBed"
        case iconHouseFilled = "icon.title.houseFilled"
        case iconHouseModern = "icon.title.houseModern"
        case iconHousePerson = "icon.title.housePerson"
        case iconImage = "icon.title.image"
        case iconInfo = "icon.title.info"
        case iconInstagram = "icon.title.instagram"
        case iconJetski = "icon.title.jetski"
        case iconKey = "icon.title.key"
        case iconLamp = "icon.title.lamp"
        case iconLandscape = "icon.title.landscape"
        case iconWashingMachine = "icon.title.washingMachine"
        case iconLayers = "icon.title.layers"
        case iconLeaf = "icon.title.leaf"
        case iconLift = "icon.title.lift"
        case iconLike = "icon.title.like"
        case iconLink = "icon.title.link"
        case iconLinkExternal = "icon.title.linkExternal"
        case iconListSort = "icon.title.listSort"
        case iconLockShield = "icon.title.lockShield"
        case iconLogout = "icon.title.logout"
        case iconMail = "icon.title.mail"
        case iconMailbox = "icon.title.mailbox"
        case iconGearManual = "icon.title.gearManual"
        case iconMap = "icon.title.map"
        case iconMessages = "icon.title.messages"
        case iconMessagesFilled = "icon.title.messagesFilled"
        case iconMinus = "icon.title.minus"
        case iconMixer = "icon.title.mixer"
        case iconMoney = "icon.title.money"
        case iconMountain = "icon.title.mountain"
        case iconNorwegianMotor = "icon.title.norwegianMotor"
        case iconNoSmoking = "icon.title.noSmoking"
        case iconOfficeDesk = "icon.title.officeDesk"
        case iconOrganize = "icon.title.organize"
        case iconParking = "icon.title.parking"
        case iconPhone = "icon.title.phone"
        case iconPhoneScratched = "icon.title.phoneScratched"
        case iconPhoneUsed = "icon.title.phoneUsed"
        case iconPictureStack = "icon.title.pictureStack"
        case iconPinMarker = "icon.title.pinMarker"
        case iconPinRound = "icon.title.pinRound"
        case iconPlaneLand = "icon.title.planeLand"
        case iconPlaneTakeOff = "icon.title.planeTakeOff"
        case iconTicket = "icon.title.ticket"
        case iconPlay = "icon.title.play"
        case iconPlayhouse = "icon.title.playhouse"
        case iconPlus = "icon.title.plus"
        case iconRocket = "icon.title.rocket"
        case iconProductBump = "icon.title.productBump"
        case iconProductCarousel = "icon.title.productCarousel"
        case iconProductHighlightListing = "icon.title.productHighlightListing"
        case iconProductNabolagsprofil = "icon.title.productNabolagsprofil"
        case iconMegaphone = "icon.title.megaphone"
        case iconProductStarred = "icon.title.productStarred"
        case iconProductTop = "icon.title.productTop"
        case iconPropeller = "icon.title.propeller"
        case iconQuestion = "icon.title.question"
        case iconRefresh = "icon.title.refresh"
        case iconRoad = "icon.title.road"
        case iconRoomService = "icon.title.roomService"
        case iconRowingBoat = "icon.title.rowingBoat"
        case iconRuler = "icon.title.ruler"
        case iconSauna = "icon.title.sauna"
        case iconScrollUp = "icon.title.scrollUp"
        case iconSearch = "icon.title.search"
        case iconSeat = "icon.title.seat"
        case iconSend = "icon.title.send"
        case iconWrench = "icon.title.service"
        case iconShare = "icon.title.wrench"
        case iconShipping = "icon.title.shipping"
        case iconShoes = "icon.title.shoes"
        case iconShoppingCart = "icon.title.shoppingCart"
        case iconShower = "icon.title.shower"
        case iconSingleCylinder = "icon.title.singleCylinder"
        case iconSkyscraper = "icon.title.skyscraper"
        case iconSmileyGood = "icon.title.smileyGood"
        case iconSmileyHappy = "icon.title.smileyHappy"
        case iconSmileyNeutral = "icon.title.smileyNeutral"
        case iconSmileySad = "icon.title.smileySad"
        case iconSorting = "icon.title.sorting"
        case iconLotusFlower = "icon.title.lotusFlower"
        case iconSparkles = "icon.title.sparkles"
        case iconSpeedometer = "icon.title.speedometer"
        case iconStairs = "icon.title.stairs"
        case iconStarCheck = "icon.title.starCheck"
        case iconStarEmpty = "icon.title.starEmpty"
        case iconStarFull = "icon.title.starFull"
        case iconStarHalf = "icon.title.starHalf"
        case iconStore = "icon.title.store"
        case iconStove = "icon.title.stove"
        case iconSuccess = "icon.title.success"
        case iconSuitcase = "icon.title.suitcase"
        case iconSupport = "icon.title.support"
        case iconSwimming = "icon.title.swimming"
        case iconTag = "icon.title.tag"
        case iconTaskList = "icon.title.taskList"
        case iconTextBold = "icon.title.textBold"
        case iconTextItalic = "icon.title.textItalic"
        case iconTextStrikethrough = "icon.title.textStrikethrough"
        case iconTextUnderline = "icon.title.textUnderline"
        case iconTheater = "icon.title.theater"
        case iconThreeSixty = "icon.title.threeSixty"
        case iconTownHouse = "icon.title.townHouse"
        case iconTrendDown = "icon.title.trendDown"
        case iconTrendFlat = "icon.title.trendFlat"
        case iconTrendUp = "icon.title.trendUp"
        case iconTv = "icon.title.tv"
        case iconX = "icon.title.twitter"
        case iconUp = "icon.title.up"
        case iconUpload = "icon.title.upload"
        case iconUser = "icon.title.user"
        case iconUserGroup = "icon.title.userGroup"
        case iconUsers = "icon.title.users"
        case iconVacuum = "icon.title.vacuum"
        case iconVerification = "icon.title.verification"
        case iconWallet = "icon.title.wallet"
        case iconWarning = "icon.title.warning"
        case iconWarranty = "icon.title.warranty"
        case iconWaterPitcher = "icon.title.waterPitcher"
        case iconWeight = "icon.title.weight"
        case iconWheelchair = "icon.title.wheelchair"
        case iconWifi = "icon.title.wifi"
        case iconTree = "icon.title.tree"
        case iconYoutube = "icon.title.youtube"
        case iconBriefcaseUser = "icon.title.briefcaseUser"
        case iconCalendarPlus = "icon.title.calendarPlus"
        case iconConfetti = "icon.title.confetti"
        case iconDraw = "icon.title.draw"
        case iconLuggage = "icon.title.luggage"
        case iconRotateLeft = "icon.title.rotateLeft"
        case iconRotateRight = "icon.title.rotateRight"
        case iconShrink = "icon.title.shrink"
        case iconSuitcaseTrolley = "icon.title.suitcaseTrolley"
        case iconTShirt = "icon.title.tShirt"
        case iconArchiveBox = "icon.title.archiveBox"
        case iconClockCountdown = "icon.title.clockCountdown"
        case iconCookie = "icon.title.cookie"
        case iconFileArrowDown = "icon.title.fileArrowDown"
        case iconMoon = "icon.title.moon"
        case iconSidebarChevronRight = "icon.title.sidebarChevronRight"
        case iconCalendarBlank = "icon.title.calendarBlank"
        case iconCode = "icon.title.code"
        case iconDeliveryKey = "icon.title.deliveryKey"
        case iconGlobe = "icon.title.globe"
        case iconSidebarChevronLeft = "icon.title.sidebarChevronLeft"
        case iconSun = "icon.title.sun"
        case iconShovel = "icon.title.shovel"
        case iconListNumbers = "icon.title.listNumbers"
        case iconTextHOne = "icon.title.textHOne"
        case iconGamingController = "icon.title.gamingController"

        case taxonomyIconPlaneTakeOff = "taxonomy.icon.title.planeTakeOff"
        case taxonomyIconAirplaneBed = "taxonomy.icon.title.airplaneBed"
        case taxonomyIconCabinHut = "taxonomy.icon.title.cabinHut"
        case taxonomyIconCarPart = "taxonomy.icon.title.carPart"
        case taxonomyIconCarRent = "taxonomy.icon.title.carRent"
        case taxonomyIconChair = "taxonomy.icon.title.chair"
        case taxonomyIconGeometricShapes = "taxonomy.icon.title.geometricShapes"
        case taxonomyIconGuitar = "taxonomy.icon.title.guitar"
        case taxonomyIconBuilding = "taxonomy.icon.title.building"
        case taxonomyIconIceSkater = "taxonomy.icon.title.iceSkater"
        case taxonomyIconBriefcase = "taxonomy.icon.title.briefcase"
        case taxonomyIconCarRight = "taxonomy.icon.title.carRight"
        case taxonomyIconMotorcycle = "taxonomy.icon.title.motorcycle"
        case taxonomyIconAnimalPaw = "taxonomy.icon.title.animalPaw"
        case taxonomyIconPhoneCheck = "taxonomy.icon.title.phoneCheck"
        case taxonomyIconHouseModern = "taxonomy.icon.title.houseModern"
        case taxonomyIconBoat = "taxonomy.icon.title.boat"
        case taxonomyIconShirt = "taxonomy.icon.title.shirt"
        case taxonomyIconPhone = "taxonomy.icon.title.phone"
        case taxonomyIconSofa = "taxonomy.icon.title.sofa"
        case taxonomyIconStoreFront = "taxonomy.icon.title.storeFront"
        case taxonomyIconStroller = "taxonomy.icon.title.stroller"
        case taxonomyIconDrill = "taxonomy.icon.title.drill"
        case taxonomyIconTractor = "taxonomy.icon.title.tractor"
        case taxonomyIconVase = "taxonomy.icon.title.vase"

        case brandIconAutovex = "brand.icon.title.autovex"
        case brandIconMittAnbud = "brand.icon.title.mittAnbud"
        case brandIconNettbil = "brand.icon.title.nettbil"
        case brandIconOikotie = "brand.icon.title.oikotie"
        case brandIconRemppatori = "brand.icon.title.remppatori"
        case brandIconQasa = "brand.icon.title.qasa"

        case brandLogoAutovex = "brand.logo.title.autovex"
        case brandLogoBilbasen = "brand.logo.title.bilbasen"
        case brandLogoBlocket = "brand.logo.title.blocket"
        case brandLogoDba = "brand.logo.title.dba"
        case brandLogoFinn = "brand.logo.title.finn"
        case brandLogoNettbil = "brand.logo.title.nettbil"
        case brandLogoOikotie = "brand.logo.title.oikotie"
        case brandLogoQasa = "brand.logo.title.qasa"
        case brandLogoTori = "brand.logo.title.tori"
        case brandLogoVend = "brand.logo.title.vend"
        case brandLogoVendPro = "brand.logo.title.vendPro"

        var localized: String {
            self.rawValue.localized
        }
    }
}

public extension String {
    var localized: String {
        return LanguageManager.shared.localizedString(forKey: self)
    }
}

class LanguageManager {
    static let shared = LanguageManager()

    private var bundle: Bundle?

    func setLanguage(for theme: Warp.Brand = Warp.Theme) {
        var language: String
        switch Warp.Theme {
        case .finn:
            language = "nb-NO"
        case .tori:
            language = "fi"
        case .dba:
            language = "da"
        case .blocket:
            language = "sv"
        case .vend, .neutral:
            language = "en"
        }
//        language = "en"
        guard let path = Bundle.module.path(forResource: language, ofType: "lproj"),
              let bundle = Bundle(path: path) else {
            self.bundle = .module
            return
        }
        self.bundle = bundle
    }

    func localizedString(forKey key: String) -> String {
        return bundle?.localizedString(forKey: key, value: nil, table: nil) ?? key
    }
}
