import SwiftUI

// Generated on Thu, 12 Dec 2024 10:09:30 GMT by https://github.com/warp-ds/tokens
public struct DatavizTokenProvider {
    public var datafillPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue400) }
    public var datafillPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue300) }
    public var datafillSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray400) }
    public var datafillSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray300) }
    public var datafillCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var datafillCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo700, darkModeColor: DatavizColors.indigo100) }
    public var datafillCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var datafillCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var datafillCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink500, darkModeColor: DatavizColors.pink400) }
    public var datafillCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink600, darkModeColor: DatavizColors.pink300) }
    public var datafillCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green400) }
    public var datafillCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green300) }
    public var datafillCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange600, darkModeColor: DatavizColors.orange400) }
    public var datafillCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange300) }
    public var datafillCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var datafillCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal100) }
    public var datafillCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue500, darkModeColor: DatavizColors.blue400) }
    public var datafillCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue300) }
    public var datafillCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray100) }
    public var datafillCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray50) }
    public var datafillPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green300) }
    public var datafillPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green200) }
    public var datafillWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var datafillWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var datafillNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red600, darkModeColor: DatavizColors.red400) }
    public var datafillNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red300) }
    public var datafillNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray200) }
    public var datafillNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray100) }
    public var datafillPrimarySubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.blue100, darkModeColor: DatavizColors.blue800) }
    public var datafillPrimarySubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue200, darkModeColor: DatavizColors.blue700) }
    public var datafillSecondarySubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.gray100, darkModeColor: DatavizColors.gray800) }
    public var datafillSecondarySubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray200, darkModeColor: DatavizColors.gray700) }
    public var datafillCategory1Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo200, darkModeColor: DatavizColors.indigo800) }
    public var datafillCategory1SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo300, darkModeColor: DatavizColors.indigo700) }
    public var datafillCategory2Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow100, darkModeColor: DatavizColors.yellow800) }
    public var datafillCategory2SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow200, darkModeColor: DatavizColors.yellow700) }
    public var datafillCategory3Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.pink100, darkModeColor: DatavizColors.pink800) }
    public var datafillCategory3SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink200, darkModeColor: DatavizColors.pink700) }
    public var datafillCategory4Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.green100, darkModeColor: DatavizColors.green800) }
    public var datafillCategory4SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green200, darkModeColor: DatavizColors.green700) }
    public var datafillCategory5Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.orange200, darkModeColor: DatavizColors.orange800) }
    public var datafillCategory5SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange300, darkModeColor: DatavizColors.orange700) }
    public var datafillCategory6Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.teal200, darkModeColor: DatavizColors.teal800) }
    public var datafillCategory6SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal300, darkModeColor: DatavizColors.teal700) }
    public var datafillCategory7Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.blue100, darkModeColor: DatavizColors.blue800) }
    public var datafillCategory7SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue200, darkModeColor: DatavizColors.blue700) }
    public var datafillCategory8Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.gray200, darkModeColor: DatavizColors.gray800) }
    public var datafillCategory8SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray300, darkModeColor: DatavizColors.gray700) }
    public var datafillPositiveSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.green100, darkModeColor: DatavizColors.green800) }
    public var datafillPositiveSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green200, darkModeColor: DatavizColors.green700) }
    public var datafillWarningSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow100, darkModeColor: DatavizColors.yellow800) }
    public var datafillWarningSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow200, darkModeColor: DatavizColors.yellow700) }
    public var datafillNegativeSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.red200, darkModeColor: DatavizColors.red800) }
    public var datafillNegativeSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red300, darkModeColor: DatavizColors.red700) }
    public var datafillNeutralSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.gray200, darkModeColor: DatavizColors.gray800) }
    public var datafillNeutralSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray300, darkModeColor: DatavizColors.gray700) }
    public var datalinePrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue300) }
    public var datalinePrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue700, darkModeColor: DatavizColors.blue100) }
    public var datalineSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray400) }
    public var datalineSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var datalineCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var datalineCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo800, darkModeColor: DatavizColors.indigo50) }
    public var datalineCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var datalineCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow50) }
    public var datalineCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink500, darkModeColor: DatavizColors.pink400) }
    public var datalineCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink650, darkModeColor: DatavizColors.pink200) }
    public var datalineCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green400) }
    public var datalineCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var datalineCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange400) }
    public var datalineCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange800, darkModeColor: DatavizColors.orange200) }
    public var datalineCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal200) }
    public var datalineCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal900, darkModeColor: DatavizColors.teal50) }
    public var datalineCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue500, darkModeColor: DatavizColors.blue400) }
    public var datalineCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var datalineCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray900, darkModeColor: DatavizColors.gray50) }
    public var datalineCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray200) }
    public var datalinePositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green300) }
    public var datalinePositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green100) }
    public var datalineWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var datalineWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow50) }
    public var datalineNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red600, darkModeColor: DatavizColors.red400) }
    public var datalineNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red700, darkModeColor: DatavizColors.red200) }
    public var datalineNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray200) }
    public var datalineNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray50) }
    public var databorderPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue400) }
    public var databorderPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue300) }
    public var databorderSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray400) }
    public var databorderSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray300) }
    public var databorderCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var databorderCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo700, darkModeColor: DatavizColors.indigo100) }
    public var databorderCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var databorderCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var databorderCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink500, darkModeColor: DatavizColors.pink400) }
    public var databorderCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink600, darkModeColor: DatavizColors.pink300) }
    public var databorderCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green400) }
    public var databorderCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green300) }
    public var databorderCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange600, darkModeColor: DatavizColors.orange400) }
    public var databorderCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange300) }
    public var databorderCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var databorderCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal100) }
    public var databorderCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue500, darkModeColor: DatavizColors.blue400) }
    public var databorderCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue300) }
    public var databorderCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray100) }
    public var databorderCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray50) }
    public var databorderPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green300) }
    public var databorderPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green200) }
    public var databorderWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var databorderWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var databorderNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red600, darkModeColor: DatavizColors.red400) }
    public var databorderNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red300) }
    public var databorderNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray200) }
    public var databorderNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray100) }
    public var datatextPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var datatextPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue800, darkModeColor: DatavizColors.blue50) }
    public var datatextSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var datatextSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray800, darkModeColor: DatavizColors.gray50) }
    public var datatextCategorical1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var datatextCategorical1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo800, darkModeColor: DatavizColors.indigo50) }
    public var datatextCategorical2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var datatextCategorical2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow800, darkModeColor: DatavizColors.yellow50) }
    public var datatextCategorical3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink650, darkModeColor: DatavizColors.pink200) }
    public var datatextCategorical3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink800, darkModeColor: DatavizColors.pink50) }
    public var datatextCategorical4: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var datatextCategorical4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green800, darkModeColor: DatavizColors.green50) }
    public var datatextCategorical5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange200) }
    public var datatextCategorical5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange800, darkModeColor: DatavizColors.orange50) }
    public var datatextCategorical6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var datatextCategorical6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal800, darkModeColor: DatavizColors.teal50) }
    public var datatextCategorical7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var datatextCategorical7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue800, darkModeColor: DatavizColors.blue50) }
    public var datatextCategorical8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var datatextCategorical8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray800, darkModeColor: DatavizColors.gray50) }
    public var datatextPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var datatextPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green800, darkModeColor: DatavizColors.green50) }
    public var datatextWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var datatextWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow800, darkModeColor: DatavizColors.yellow50) }
    public var datatextNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red200) }
    public var datatextNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red800, darkModeColor: DatavizColors.red50) }
    public var datatextNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var datatextNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray800, darkModeColor: DatavizColors.gray50) }
    public var dataiconPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var dataiconPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue700, darkModeColor: DatavizColors.blue100) }
    public var dataiconSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var dataiconSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray100) }
    public var dataiconCategorical1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var dataiconCategorical1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo700, darkModeColor: DatavizColors.indigo100) }
    public var dataiconCategorical2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var dataiconCategorical2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow700, darkModeColor: DatavizColors.yellow100) }
    public var dataiconCategorical3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink650, darkModeColor: DatavizColors.pink200) }
    public var dataiconCategorical3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink700, darkModeColor: DatavizColors.pink100) }
    public var dataiconCategorical4: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var dataiconCategorical4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green700, darkModeColor: DatavizColors.green100) }
    public var dataiconCategorical5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange200) }
    public var dataiconCategorical5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange700, darkModeColor: DatavizColors.orange100) }
    public var dataiconCategorical6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var dataiconCategorical6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal100) }
    public var dataiconCategorical7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var dataiconCategorical7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue700, darkModeColor: DatavizColors.blue100) }
    public var dataiconCategorical8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var dataiconCategorical8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray100) }
    public var dataiconPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var dataiconPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green700, darkModeColor: DatavizColors.green100) }
    public var dataiconWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var dataiconWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow700, darkModeColor: DatavizColors.yellow100) }
    public var dataiconNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red200) }
    public var dataiconNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red700, darkModeColor: DatavizColors.red100) }
    public var dataiconNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var dataiconNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray100) }
}

public struct DatavizUITokenProvider {
    public var datafillPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue400) }
    public var datafillPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue300) }
    public var datafillSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray400) }
    public var datafillSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray300) }
    public var datafillCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var datafillCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo700, darkModeColor: DatavizUIColors.indigo100) }
    public var datafillCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var datafillCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var datafillCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink500, darkModeColor: DatavizUIColors.pink400) }
    public var datafillCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink600, darkModeColor: DatavizUIColors.pink300) }
    public var datafillCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green400) }
    public var datafillCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green300) }
    public var datafillCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange600, darkModeColor: DatavizUIColors.orange400) }
    public var datafillCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange300) }
    public var datafillCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var datafillCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal100) }
    public var datafillCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue500, darkModeColor: DatavizUIColors.blue400) }
    public var datafillCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue300) }
    public var datafillCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray100) }
    public var datafillCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray50) }
    public var datafillPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green300) }
    public var datafillPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green200) }
    public var datafillWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var datafillWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var datafillNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red600, darkModeColor: DatavizUIColors.red400) }
    public var datafillNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red300) }
    public var datafillNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray200) }
    public var datafillNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray100) }
    public var datafillPrimarySubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue100, darkModeColor: DatavizUIColors.blue800) }
    public var datafillPrimarySubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue200, darkModeColor: DatavizUIColors.blue700) }
    public var datafillSecondarySubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray100, darkModeColor: DatavizUIColors.gray800) }
    public var datafillSecondarySubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray200, darkModeColor: DatavizUIColors.gray700) }
    public var datafillCategory1Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo200, darkModeColor: DatavizUIColors.indigo800) }
    public var datafillCategory1SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo300, darkModeColor: DatavizUIColors.indigo700) }
    public var datafillCategory2Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow100, darkModeColor: DatavizUIColors.yellow800) }
    public var datafillCategory2SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow200, darkModeColor: DatavizUIColors.yellow700) }
    public var datafillCategory3Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink100, darkModeColor: DatavizUIColors.pink800) }
    public var datafillCategory3SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink200, darkModeColor: DatavizUIColors.pink700) }
    public var datafillCategory4Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green100, darkModeColor: DatavizUIColors.green800) }
    public var datafillCategory4SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green200, darkModeColor: DatavizUIColors.green700) }
    public var datafillCategory5Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange200, darkModeColor: DatavizUIColors.orange800) }
    public var datafillCategory5SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange300, darkModeColor: DatavizUIColors.orange700) }
    public var datafillCategory6Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal200, darkModeColor: DatavizUIColors.teal800) }
    public var datafillCategory6SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal300, darkModeColor: DatavizUIColors.teal700) }
    public var datafillCategory7Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue100, darkModeColor: DatavizUIColors.blue800) }
    public var datafillCategory7SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue200, darkModeColor: DatavizUIColors.blue700) }
    public var datafillCategory8Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray200, darkModeColor: DatavizUIColors.gray800) }
    public var datafillCategory8SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray300, darkModeColor: DatavizUIColors.gray700) }
    public var datafillPositiveSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green100, darkModeColor: DatavizUIColors.green800) }
    public var datafillPositiveSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green200, darkModeColor: DatavizUIColors.green700) }
    public var datafillWarningSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow100, darkModeColor: DatavizUIColors.yellow800) }
    public var datafillWarningSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow200, darkModeColor: DatavizUIColors.yellow700) }
    public var datafillNegativeSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red200, darkModeColor: DatavizUIColors.red800) }
    public var datafillNegativeSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red300, darkModeColor: DatavizUIColors.red700) }
    public var datafillNeutralSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray200, darkModeColor: DatavizUIColors.gray800) }
    public var datafillNeutralSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray300, darkModeColor: DatavizUIColors.gray700) }
    public var datalinePrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue300) }
    public var datalinePrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue700, darkModeColor: DatavizUIColors.blue100) }
    public var datalineSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray400) }
    public var datalineSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var datalineCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var datalineCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo800, darkModeColor: DatavizUIColors.indigo50) }
    public var datalineCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var datalineCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow50) }
    public var datalineCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink500, darkModeColor: DatavizUIColors.pink400) }
    public var datalineCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink650, darkModeColor: DatavizUIColors.pink200) }
    public var datalineCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green400) }
    public var datalineCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var datalineCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange400) }
    public var datalineCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange800, darkModeColor: DatavizUIColors.orange200) }
    public var datalineCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal200) }
    public var datalineCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal900, darkModeColor: DatavizUIColors.teal50) }
    public var datalineCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue500, darkModeColor: DatavizUIColors.blue400) }
    public var datalineCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var datalineCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray900, darkModeColor: DatavizUIColors.gray50) }
    public var datalineCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray200) }
    public var datalinePositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green300) }
    public var datalinePositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green100) }
    public var datalineWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var datalineWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow50) }
    public var datalineNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red600, darkModeColor: DatavizUIColors.red400) }
    public var datalineNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red700, darkModeColor: DatavizUIColors.red200) }
    public var datalineNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray200) }
    public var datalineNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray50) }
    public var databorderPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue400) }
    public var databorderPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue300) }
    public var databorderSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray400) }
    public var databorderSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray300) }
    public var databorderCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var databorderCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo700, darkModeColor: DatavizUIColors.indigo100) }
    public var databorderCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var databorderCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var databorderCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink500, darkModeColor: DatavizUIColors.pink400) }
    public var databorderCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink600, darkModeColor: DatavizUIColors.pink300) }
    public var databorderCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green400) }
    public var databorderCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green300) }
    public var databorderCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange600, darkModeColor: DatavizUIColors.orange400) }
    public var databorderCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange300) }
    public var databorderCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var databorderCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal100) }
    public var databorderCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue500, darkModeColor: DatavizUIColors.blue400) }
    public var databorderCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue300) }
    public var databorderCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray100) }
    public var databorderCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray50) }
    public var databorderPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green300) }
    public var databorderPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green200) }
    public var databorderWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var databorderWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var databorderNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red600, darkModeColor: DatavizUIColors.red400) }
    public var databorderNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red300) }
    public var databorderNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray200) }
    public var databorderNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray100) }
    public var datatextPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var datatextPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue800, darkModeColor: DatavizUIColors.blue50) }
    public var datatextSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var datatextSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray800, darkModeColor: DatavizUIColors.gray50) }
    public var datatextCategorical1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var datatextCategorical1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo800, darkModeColor: DatavizUIColors.indigo50) }
    public var datatextCategorical2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var datatextCategorical2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow800, darkModeColor: DatavizUIColors.yellow50) }
    public var datatextCategorical3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink650, darkModeColor: DatavizUIColors.pink200) }
    public var datatextCategorical3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink800, darkModeColor: DatavizUIColors.pink50) }
    public var datatextCategorical4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var datatextCategorical4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green800, darkModeColor: DatavizUIColors.green50) }
    public var datatextCategorical5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange200) }
    public var datatextCategorical5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange800, darkModeColor: DatavizUIColors.orange50) }
    public var datatextCategorical6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var datatextCategorical6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal800, darkModeColor: DatavizUIColors.teal50) }
    public var datatextCategorical7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var datatextCategorical7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue800, darkModeColor: DatavizUIColors.blue50) }
    public var datatextCategorical8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var datatextCategorical8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray800, darkModeColor: DatavizUIColors.gray50) }
    public var datatextPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var datatextPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green800, darkModeColor: DatavizUIColors.green50) }
    public var datatextWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var datatextWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow800, darkModeColor: DatavizUIColors.yellow50) }
    public var datatextNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red200) }
    public var datatextNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red800, darkModeColor: DatavizUIColors.red50) }
    public var datatextNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var datatextNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray800, darkModeColor: DatavizUIColors.gray50) }
    public var dataiconPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var dataiconPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue700, darkModeColor: DatavizUIColors.blue100) }
    public var dataiconSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var dataiconSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray100) }
    public var dataiconCategorical1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var dataiconCategorical1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo700, darkModeColor: DatavizUIColors.indigo100) }
    public var dataiconCategorical2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var dataiconCategorical2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow700, darkModeColor: DatavizUIColors.yellow100) }
    public var dataiconCategorical3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink650, darkModeColor: DatavizUIColors.pink200) }
    public var dataiconCategorical3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink700, darkModeColor: DatavizUIColors.pink100) }
    public var dataiconCategorical4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var dataiconCategorical4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green700, darkModeColor: DatavizUIColors.green100) }
    public var dataiconCategorical5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange200) }
    public var dataiconCategorical5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange700, darkModeColor: DatavizUIColors.orange100) }
    public var dataiconCategorical6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var dataiconCategorical6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal100) }
    public var dataiconCategorical7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var dataiconCategorical7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue700, darkModeColor: DatavizUIColors.blue100) }
    public var dataiconCategorical8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var dataiconCategorical8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray100) }
    public var dataiconPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var dataiconPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green700, darkModeColor: DatavizUIColors.green100) }
    public var dataiconWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var dataiconWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow700, darkModeColor: DatavizUIColors.yellow100) }
    public var dataiconNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red200) }
    public var dataiconNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red700, darkModeColor: DatavizUIColors.red100) }
    public var dataiconNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var dataiconNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray100) }
}
