import SwiftUI

// Generated on Fri, 13 Dec 2024 14:38:41 GMT by https://github.com/warp-ds/tokens
public struct DatavizTokenProvider {
    public var fillPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue400) }
    public var fillPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue300) }
    public var fillSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray400) }
    public var fillSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray300) }
    public var fillCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var fillCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo700, darkModeColor: DatavizColors.indigo100) }
    public var fillCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var fillCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var fillCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink500, darkModeColor: DatavizColors.pink400) }
    public var fillCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink600, darkModeColor: DatavizColors.pink300) }
    public var fillCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green400) }
    public var fillCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green300) }
    public var fillCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange600, darkModeColor: DatavizColors.orange400) }
    public var fillCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange300) }
    public var fillCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var fillCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal100) }
    public var fillCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue500, darkModeColor: DatavizColors.blue400) }
    public var fillCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue300) }
    public var fillCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray100) }
    public var fillCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray50) }
    public var fillPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green300) }
    public var fillPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green200) }
    public var fillWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var fillWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var fillNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red600, darkModeColor: DatavizColors.red400) }
    public var fillNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red300) }
    public var fillNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray200) }
    public var fillNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray100) }
    public var fillPrimarySubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.blue100, darkModeColor: DatavizColors.blue800) }
    public var fillPrimarySubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue200, darkModeColor: DatavizColors.blue700) }
    public var fillSecondarySubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.gray100, darkModeColor: DatavizColors.gray800) }
    public var fillSecondarySubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray200, darkModeColor: DatavizColors.gray700) }
    public var fillCategory1Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo200, darkModeColor: DatavizColors.indigo800) }
    public var fillCategory1SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo300, darkModeColor: DatavizColors.indigo700) }
    public var fillCategory2Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow100, darkModeColor: DatavizColors.yellow800) }
    public var fillCategory2SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow200, darkModeColor: DatavizColors.yellow700) }
    public var fillCategory3Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.pink100, darkModeColor: DatavizColors.pink800) }
    public var fillCategory3SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink200, darkModeColor: DatavizColors.pink700) }
    public var fillCategory4Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.green100, darkModeColor: DatavizColors.green800) }
    public var fillCategory4SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green200, darkModeColor: DatavizColors.green700) }
    public var fillCategory5Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.orange200, darkModeColor: DatavizColors.orange800) }
    public var fillCategory5SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange300, darkModeColor: DatavizColors.orange700) }
    public var fillCategory6Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.teal200, darkModeColor: DatavizColors.teal800) }
    public var fillCategory6SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal300, darkModeColor: DatavizColors.teal700) }
    public var fillCategory7Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.blue100, darkModeColor: DatavizColors.blue800) }
    public var fillCategory7SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue200, darkModeColor: DatavizColors.blue700) }
    public var fillCategory8Subtle: Color { Color.dynamicColor(defaultColor: DatavizColors.gray200, darkModeColor: DatavizColors.gray800) }
    public var fillCategory8SubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray300, darkModeColor: DatavizColors.gray700) }
    public var fillPositiveSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.green100, darkModeColor: DatavizColors.green800) }
    public var fillPositiveSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green200, darkModeColor: DatavizColors.green700) }
    public var fillWarningSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow100, darkModeColor: DatavizColors.yellow800) }
    public var fillWarningSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow200, darkModeColor: DatavizColors.yellow700) }
    public var fillNegativeSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.red200, darkModeColor: DatavizColors.red800) }
    public var fillNegativeSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red300, darkModeColor: DatavizColors.red700) }
    public var fillNeutralSubtle: Color { Color.dynamicColor(defaultColor: DatavizColors.gray200, darkModeColor: DatavizColors.gray800) }
    public var fillNeutralSubtleFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray300, darkModeColor: DatavizColors.gray700) }
    public var linePrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue300) }
    public var linePrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue700, darkModeColor: DatavizColors.blue100) }
    public var lineSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray400) }
    public var lineSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var lineCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var lineCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo800, darkModeColor: DatavizColors.indigo50) }
    public var lineCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var lineCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow50) }
    public var lineCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink500, darkModeColor: DatavizColors.pink400) }
    public var lineCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink650, darkModeColor: DatavizColors.pink200) }
    public var lineCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green400) }
    public var lineCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var lineCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange400) }
    public var lineCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange800, darkModeColor: DatavizColors.orange200) }
    public var lineCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal200) }
    public var lineCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal900, darkModeColor: DatavizColors.teal50) }
    public var lineCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue500, darkModeColor: DatavizColors.blue400) }
    public var lineCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var lineCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray900, darkModeColor: DatavizColors.gray50) }
    public var lineCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray200) }
    public var linePositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green300) }
    public var linePositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green100) }
    public var lineWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var lineWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow50) }
    public var lineNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red600, darkModeColor: DatavizColors.red400) }
    public var lineNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red700, darkModeColor: DatavizColors.red200) }
    public var lineNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray200) }
    public var lineNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray50) }
    public var borderPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue400) }
    public var borderPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue300) }
    public var borderSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray400) }
    public var borderSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray300) }
    public var borderCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var borderCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo700, darkModeColor: DatavizColors.indigo100) }
    public var borderCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var borderCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var borderCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink500, darkModeColor: DatavizColors.pink400) }
    public var borderCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink600, darkModeColor: DatavizColors.pink300) }
    public var borderCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green400) }
    public var borderCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green300) }
    public var borderCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange600, darkModeColor: DatavizColors.orange400) }
    public var borderCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange300) }
    public var borderCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var borderCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal100) }
    public var borderCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue500, darkModeColor: DatavizColors.blue400) }
    public var borderCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue600, darkModeColor: DatavizColors.blue300) }
    public var borderCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray500, darkModeColor: DatavizColors.gray100) }
    public var borderCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray50) }
    public var borderPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green500, darkModeColor: DatavizColors.green300) }
    public var borderPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green600, darkModeColor: DatavizColors.green200) }
    public var borderWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow500, darkModeColor: DatavizColors.yellow200) }
    public var borderWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow600, darkModeColor: DatavizColors.yellow100) }
    public var borderNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red600, darkModeColor: DatavizColors.red400) }
    public var borderNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red300) }
    public var borderNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray600, darkModeColor: DatavizColors.gray200) }
    public var borderNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray100) }
    public var textPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var textPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue800, darkModeColor: DatavizColors.blue50) }
    public var textSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var textSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray800, darkModeColor: DatavizColors.gray50) }
    public var textCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var textCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo800, darkModeColor: DatavizColors.indigo50) }
    public var textCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var textCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow800, darkModeColor: DatavizColors.yellow50) }
    public var textCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink650, darkModeColor: DatavizColors.pink200) }
    public var textCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink800, darkModeColor: DatavizColors.pink50) }
    public var textCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var textCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green800, darkModeColor: DatavizColors.green50) }
    public var textCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange200) }
    public var textCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange800, darkModeColor: DatavizColors.orange50) }
    public var textCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var textCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal800, darkModeColor: DatavizColors.teal50) }
    public var textCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var textCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue800, darkModeColor: DatavizColors.blue50) }
    public var textCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var textCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray800, darkModeColor: DatavizColors.gray50) }
    public var textPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var textPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green800, darkModeColor: DatavizColors.green50) }
    public var textWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var textWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow800, darkModeColor: DatavizColors.yellow50) }
    public var textNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red200) }
    public var textNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red800, darkModeColor: DatavizColors.red50) }
    public var textNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var textNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray800, darkModeColor: DatavizColors.gray50) }
    public var iconPrimary: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var iconPrimaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue700, darkModeColor: DatavizColors.blue100) }
    public var iconSecondary: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var iconSecondaryFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray100) }
    public var iconCategory1: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo650, darkModeColor: DatavizColors.indigo200) }
    public var iconCategory1Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.indigo700, darkModeColor: DatavizColors.indigo100) }
    public var iconCategory2: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var iconCategory2Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow700, darkModeColor: DatavizColors.yellow100) }
    public var iconCategory3: Color { Color.dynamicColor(defaultColor: DatavizColors.pink650, darkModeColor: DatavizColors.pink200) }
    public var iconCategory3Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.pink700, darkModeColor: DatavizColors.pink100) }
    public var iconCategory4: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var iconCategory4Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.green700, darkModeColor: DatavizColors.green100) }
    public var iconCategory5: Color { Color.dynamicColor(defaultColor: DatavizColors.orange650, darkModeColor: DatavizColors.orange200) }
    public var iconCategory5Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.orange700, darkModeColor: DatavizColors.orange100) }
    public var iconCategory6: Color { Color.dynamicColor(defaultColor: DatavizColors.teal650, darkModeColor: DatavizColors.teal200) }
    public var iconCategory6Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.teal700, darkModeColor: DatavizColors.teal100) }
    public var iconCategory7: Color { Color.dynamicColor(defaultColor: DatavizColors.blue650, darkModeColor: DatavizColors.blue200) }
    public var iconCategory7Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.blue700, darkModeColor: DatavizColors.blue100) }
    public var iconCategory8: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var iconCategory8Focus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray100) }
    public var iconPositive: Color { Color.dynamicColor(defaultColor: DatavizColors.green650, darkModeColor: DatavizColors.green200) }
    public var iconPositiveFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.green700, darkModeColor: DatavizColors.green100) }
    public var iconWarning: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow650, darkModeColor: DatavizColors.yellow200) }
    public var iconWarningFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.yellow700, darkModeColor: DatavizColors.yellow100) }
    public var iconNegative: Color { Color.dynamicColor(defaultColor: DatavizColors.red650, darkModeColor: DatavizColors.red200) }
    public var iconNegativeFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.red700, darkModeColor: DatavizColors.red100) }
    public var iconNeutral: Color { Color.dynamicColor(defaultColor: DatavizColors.gray650, darkModeColor: DatavizColors.gray200) }
    public var iconNeutralFocus: Color { Color.dynamicColor(defaultColor: DatavizColors.gray700, darkModeColor: DatavizColors.gray100) }
}

public struct DatavizUITokenProvider {
    public var fillPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue400) }
    public var fillPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue300) }
    public var fillSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray400) }
    public var fillSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray300) }
    public var fillCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var fillCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo700, darkModeColor: DatavizUIColors.indigo100) }
    public var fillCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var fillCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var fillCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink500, darkModeColor: DatavizUIColors.pink400) }
    public var fillCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink600, darkModeColor: DatavizUIColors.pink300) }
    public var fillCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green400) }
    public var fillCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green300) }
    public var fillCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange600, darkModeColor: DatavizUIColors.orange400) }
    public var fillCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange300) }
    public var fillCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var fillCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal100) }
    public var fillCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue500, darkModeColor: DatavizUIColors.blue400) }
    public var fillCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue300) }
    public var fillCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray100) }
    public var fillCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray50) }
    public var fillPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green300) }
    public var fillPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green200) }
    public var fillWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var fillWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var fillNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red600, darkModeColor: DatavizUIColors.red400) }
    public var fillNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red300) }
    public var fillNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray200) }
    public var fillNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray100) }
    public var fillPrimarySubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue100, darkModeColor: DatavizUIColors.blue800) }
    public var fillPrimarySubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue200, darkModeColor: DatavizUIColors.blue700) }
    public var fillSecondarySubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray100, darkModeColor: DatavizUIColors.gray800) }
    public var fillSecondarySubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray200, darkModeColor: DatavizUIColors.gray700) }
    public var fillCategory1Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo200, darkModeColor: DatavizUIColors.indigo800) }
    public var fillCategory1SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo300, darkModeColor: DatavizUIColors.indigo700) }
    public var fillCategory2Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow100, darkModeColor: DatavizUIColors.yellow800) }
    public var fillCategory2SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow200, darkModeColor: DatavizUIColors.yellow700) }
    public var fillCategory3Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink100, darkModeColor: DatavizUIColors.pink800) }
    public var fillCategory3SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink200, darkModeColor: DatavizUIColors.pink700) }
    public var fillCategory4Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green100, darkModeColor: DatavizUIColors.green800) }
    public var fillCategory4SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green200, darkModeColor: DatavizUIColors.green700) }
    public var fillCategory5Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange200, darkModeColor: DatavizUIColors.orange800) }
    public var fillCategory5SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange300, darkModeColor: DatavizUIColors.orange700) }
    public var fillCategory6Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal200, darkModeColor: DatavizUIColors.teal800) }
    public var fillCategory6SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal300, darkModeColor: DatavizUIColors.teal700) }
    public var fillCategory7Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue100, darkModeColor: DatavizUIColors.blue800) }
    public var fillCategory7SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue200, darkModeColor: DatavizUIColors.blue700) }
    public var fillCategory8Subtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray200, darkModeColor: DatavizUIColors.gray800) }
    public var fillCategory8SubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray300, darkModeColor: DatavizUIColors.gray700) }
    public var fillPositiveSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green100, darkModeColor: DatavizUIColors.green800) }
    public var fillPositiveSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green200, darkModeColor: DatavizUIColors.green700) }
    public var fillWarningSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow100, darkModeColor: DatavizUIColors.yellow800) }
    public var fillWarningSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow200, darkModeColor: DatavizUIColors.yellow700) }
    public var fillNegativeSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red200, darkModeColor: DatavizUIColors.red800) }
    public var fillNegativeSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red300, darkModeColor: DatavizUIColors.red700) }
    public var fillNeutralSubtle: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray200, darkModeColor: DatavizUIColors.gray800) }
    public var fillNeutralSubtleFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray300, darkModeColor: DatavizUIColors.gray700) }
    public var linePrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue300) }
    public var linePrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue700, darkModeColor: DatavizUIColors.blue100) }
    public var lineSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray400) }
    public var lineSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var lineCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var lineCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo800, darkModeColor: DatavizUIColors.indigo50) }
    public var lineCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var lineCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow50) }
    public var lineCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink500, darkModeColor: DatavizUIColors.pink400) }
    public var lineCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink650, darkModeColor: DatavizUIColors.pink200) }
    public var lineCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green400) }
    public var lineCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var lineCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange400) }
    public var lineCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange800, darkModeColor: DatavizUIColors.orange200) }
    public var lineCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal200) }
    public var lineCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal900, darkModeColor: DatavizUIColors.teal50) }
    public var lineCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue500, darkModeColor: DatavizUIColors.blue400) }
    public var lineCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var lineCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray900, darkModeColor: DatavizUIColors.gray50) }
    public var lineCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray200) }
    public var linePositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green300) }
    public var linePositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green100) }
    public var lineWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var lineWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow50) }
    public var lineNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red600, darkModeColor: DatavizUIColors.red400) }
    public var lineNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red700, darkModeColor: DatavizUIColors.red200) }
    public var lineNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray200) }
    public var lineNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray50) }
    public var borderPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue400) }
    public var borderPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue300) }
    public var borderSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray400) }
    public var borderSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray300) }
    public var borderCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var borderCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo700, darkModeColor: DatavizUIColors.indigo100) }
    public var borderCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var borderCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var borderCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink500, darkModeColor: DatavizUIColors.pink400) }
    public var borderCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink600, darkModeColor: DatavizUIColors.pink300) }
    public var borderCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green400) }
    public var borderCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green300) }
    public var borderCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange600, darkModeColor: DatavizUIColors.orange400) }
    public var borderCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange300) }
    public var borderCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var borderCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal100) }
    public var borderCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue500, darkModeColor: DatavizUIColors.blue400) }
    public var borderCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue600, darkModeColor: DatavizUIColors.blue300) }
    public var borderCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray500, darkModeColor: DatavizUIColors.gray100) }
    public var borderCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray50) }
    public var borderPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green500, darkModeColor: DatavizUIColors.green300) }
    public var borderPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green600, darkModeColor: DatavizUIColors.green200) }
    public var borderWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow500, darkModeColor: DatavizUIColors.yellow200) }
    public var borderWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow600, darkModeColor: DatavizUIColors.yellow100) }
    public var borderNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red600, darkModeColor: DatavizUIColors.red400) }
    public var borderNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red300) }
    public var borderNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray600, darkModeColor: DatavizUIColors.gray200) }
    public var borderNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray100) }
    public var textPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var textPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue800, darkModeColor: DatavizUIColors.blue50) }
    public var textSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var textSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray800, darkModeColor: DatavizUIColors.gray50) }
    public var textCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var textCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo800, darkModeColor: DatavizUIColors.indigo50) }
    public var textCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var textCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow800, darkModeColor: DatavizUIColors.yellow50) }
    public var textCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink650, darkModeColor: DatavizUIColors.pink200) }
    public var textCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink800, darkModeColor: DatavizUIColors.pink50) }
    public var textCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var textCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green800, darkModeColor: DatavizUIColors.green50) }
    public var textCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange200) }
    public var textCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange800, darkModeColor: DatavizUIColors.orange50) }
    public var textCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var textCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal800, darkModeColor: DatavizUIColors.teal50) }
    public var textCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var textCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue800, darkModeColor: DatavizUIColors.blue50) }
    public var textCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var textCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray800, darkModeColor: DatavizUIColors.gray50) }
    public var textPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var textPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green800, darkModeColor: DatavizUIColors.green50) }
    public var textWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var textWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow800, darkModeColor: DatavizUIColors.yellow50) }
    public var textNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red200) }
    public var textNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red800, darkModeColor: DatavizUIColors.red50) }
    public var textNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var textNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray800, darkModeColor: DatavizUIColors.gray50) }
    public var iconPrimary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var iconPrimaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue700, darkModeColor: DatavizUIColors.blue100) }
    public var iconSecondary: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var iconSecondaryFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray100) }
    public var iconCategory1: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo650, darkModeColor: DatavizUIColors.indigo200) }
    public var iconCategory1Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.indigo700, darkModeColor: DatavizUIColors.indigo100) }
    public var iconCategory2: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var iconCategory2Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow700, darkModeColor: DatavizUIColors.yellow100) }
    public var iconCategory3: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink650, darkModeColor: DatavizUIColors.pink200) }
    public var iconCategory3Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.pink700, darkModeColor: DatavizUIColors.pink100) }
    public var iconCategory4: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var iconCategory4Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green700, darkModeColor: DatavizUIColors.green100) }
    public var iconCategory5: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange650, darkModeColor: DatavizUIColors.orange200) }
    public var iconCategory5Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.orange700, darkModeColor: DatavizUIColors.orange100) }
    public var iconCategory6: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal650, darkModeColor: DatavizUIColors.teal200) }
    public var iconCategory6Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.teal700, darkModeColor: DatavizUIColors.teal100) }
    public var iconCategory7: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue650, darkModeColor: DatavizUIColors.blue200) }
    public var iconCategory7Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.blue700, darkModeColor: DatavizUIColors.blue100) }
    public var iconCategory8: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var iconCategory8Focus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray100) }
    public var iconPositive: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green650, darkModeColor: DatavizUIColors.green200) }
    public var iconPositiveFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.green700, darkModeColor: DatavizUIColors.green100) }
    public var iconWarning: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow650, darkModeColor: DatavizUIColors.yellow200) }
    public var iconWarningFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.yellow700, darkModeColor: DatavizUIColors.yellow100) }
    public var iconNegative: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red650, darkModeColor: DatavizUIColors.red200) }
    public var iconNegativeFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.red700, darkModeColor: DatavizUIColors.red100) }
    public var iconNeutral: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray650, darkModeColor: DatavizUIColors.gray200) }
    public var iconNeutralFocus: UIColor { UIColor.dynamicColor(defaultColor: DatavizUIColors.gray700, darkModeColor: DatavizUIColors.gray100) }
}
