import SwiftUI

// Generated on Fri, 19 Sep 2025 11:07:54 GMT by https://github.com/warp-ds/tokens
struct NeutralTokenProvider: TokenProvider {
    public var text: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.white) }
    public var textSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.gray600, darkModeColor: NeutralColors.gray400) }
    public var textStatic: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.gray900) }
    public var textPlaceholder: Color { Color.dynamicColor(defaultColor: NeutralColors.gray300, darkModeColor: NeutralColors.gray500) }
    public var textInverted: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.gray900) }
    public var textInvertedSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.gray400, darkModeColor: NeutralColors.gray600) }
    public var textInvertedStatic: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.white) }
    public var textLink: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue400) }
    public var textDisabled: Color { Color.dynamicColor(defaultColor: NeutralColors.gray300, darkModeColor: NeutralColors.gray500) }
    public var textNegative: Color { Color.dynamicColor(defaultColor: NeutralColors.red600, darkModeColor: NeutralColors.red400) }
    public var textPositive: Color { Color.dynamicColor(defaultColor: NeutralColors.green600, darkModeColor: NeutralColors.green400) }
    public var background: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.gray900) }
    public var backgroundHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray100, darkModeColor: NeutralColors.gray850) }
    public var backgroundActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray200, darkModeColor: NeutralColors.gray800) }
    public var backgroundSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.gray100, darkModeColor: NeutralColors.gray750) }
    public var backgroundSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray200, darkModeColor: NeutralColors.gray700) }
    public var backgroundSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray300, darkModeColor: NeutralColors.gray600) }
    public var backgroundDisabled: Color { Color.dynamicColor(defaultColor: NeutralColors.gray300, darkModeColor: NeutralColors.gray700) }
    public var backgroundDisabledSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.gray200, darkModeColor: NeutralColors.gray600) }
    public var backgroundSelected: Color { Color.dynamicColor(defaultColor: NeutralColors.blue50, darkModeColor: NeutralColors.blue900) }
    public var backgroundSelectedHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue100, darkModeColor: NeutralColors.blue800) }
    public var backgroundSelectedActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue200, darkModeColor: NeutralColors.blue700) }
    public var backgroundInverted: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.gray50) }
    public var backgroundPrimary: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue400) }
    public var backgroundPrimaryHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue700, darkModeColor: NeutralColors.blue300) }
    public var backgroundPrimaryActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue800, darkModeColor: NeutralColors.blue200) }
    public var backgroundPrimarySubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.blue100, darkModeColor: NeutralColors.blue850) }
    public var backgroundPrimarySubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue200, darkModeColor: NeutralColors.blue800) }
    public var backgroundPrimarySubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue300, darkModeColor: NeutralColors.blue750) }
    public var backgroundSecondary: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.white) }
    public var backgroundSecondaryHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray800, darkModeColor: NeutralColors.gray100) }
    public var backgroundSecondaryActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray700, darkModeColor: NeutralColors.gray200) }
    public var backgroundPositive: Color { Color.dynamicColor(defaultColor: NeutralColors.green600, darkModeColor: NeutralColors.green400) }
    public var backgroundPositiveHover: Color { Color.dynamicColor(defaultColor: NeutralColors.green700, darkModeColor: NeutralColors.green300) }
    public var backgroundPositiveActive: Color { Color.dynamicColor(defaultColor: NeutralColors.green800, darkModeColor: NeutralColors.green200) }
    public var backgroundPositiveSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.green50, darkModeColor: NeutralColors.green900) }
    public var backgroundPositiveSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.green100, darkModeColor: NeutralColors.green800) }
    public var backgroundPositiveSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.green200, darkModeColor: NeutralColors.green700) }
    public var backgroundNegative: Color { Color.dynamicColor(defaultColor: NeutralColors.red600, darkModeColor: NeutralColors.red400) }
    public var backgroundNegativeHover: Color { Color.dynamicColor(defaultColor: NeutralColors.red700, darkModeColor: NeutralColors.red300) }
    public var backgroundNegativeActive: Color { Color.dynamicColor(defaultColor: NeutralColors.red800, darkModeColor: NeutralColors.red200) }
    public var backgroundNegativeSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.red50, darkModeColor: NeutralColors.red900) }
    public var backgroundNegativeSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.red100, darkModeColor: NeutralColors.red800) }
    public var backgroundNegativeSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.red200, darkModeColor: NeutralColors.red700) }
    public var backgroundWarning: Color { Color.dynamicColor(defaultColor: NeutralColors.orange600, darkModeColor: NeutralColors.orange500) }
    public var backgroundWarningHover: Color { Color.dynamicColor(defaultColor: NeutralColors.orange700, darkModeColor: NeutralColors.orange400) }
    public var backgroundWarningActive: Color { Color.dynamicColor(defaultColor: NeutralColors.orange800, darkModeColor: NeutralColors.orange300) }
    public var backgroundWarningSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.orange50, darkModeColor: NeutralColors.orange900) }
    public var backgroundWarningSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.orange100, darkModeColor: NeutralColors.orange800) }
    public var backgroundWarningSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.orange200, darkModeColor: NeutralColors.orange700) }
    public var backgroundInfo: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue500) }
    public var backgroundInfoHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue700, darkModeColor: NeutralColors.blue400) }
    public var backgroundInfoActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue800, darkModeColor: NeutralColors.blue300) }
    public var backgroundInfoSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.blue50, darkModeColor: NeutralColors.blue900) }
    public var backgroundInfoSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue100, darkModeColor: NeutralColors.blue800) }
    public var backgroundInfoSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue200, darkModeColor: NeutralColors.blue700) }
    public var backgroundTransparent0: Color { Color.dynamicColor(defaultColor: NeutralColors.transparent, darkModeColor: NeutralColors.transparent) }
    public var backgroundNotification: Color { Color.dynamicColor(defaultColor: NeutralColors.red600, darkModeColor: NeutralColors.red500) }
    public var surfaceSunken: Color { Color.dynamicColor(defaultColor: NeutralColors.gray50, darkModeColor: NeutralColors.gray950) }
    public var surfaceElevated100: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.gray850) }
    public var surfaceElevated100Hover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray100, darkModeColor: NeutralColors.gray800) }
    public var surfaceElevated100Active: Color { Color.dynamicColor(defaultColor: NeutralColors.gray200, darkModeColor: NeutralColors.gray750) }
    public var surfaceElevated200: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.gray800) }
    public var surfaceElevated200Hover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray100, darkModeColor: NeutralColors.gray750) }
    public var surfaceElevated200Active: Color { Color.dynamicColor(defaultColor: NeutralColors.gray200, darkModeColor: NeutralColors.gray700) }
    public var surfaceElevated300: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.gray750) }
    public var surfaceElevated300Hover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray100, darkModeColor: NeutralColors.gray700) }
    public var surfaceElevated300Active: Color { Color.dynamicColor(defaultColor: NeutralColors.gray200, darkModeColor: NeutralColors.gray600) }
    public var border: Color { Color.dynamicColor(defaultColor: NeutralColors.gray300, darkModeColor: NeutralColors.gray600) }
    public var borderHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray400, darkModeColor: NeutralColors.gray500) }
    public var borderActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray500, darkModeColor: NeutralColors.gray400) }
    public var borderDisabled: Color { Color.dynamicColor(defaultColor: NeutralColors.gray300, darkModeColor: NeutralColors.gray700) }
    public var borderSelected: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue400) }
    public var borderSelectedHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue700, darkModeColor: NeutralColors.blue300) }
    public var borderSelectedActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue800, darkModeColor: NeutralColors.blue200) }
    public var borderInverted: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.gray900) }
    public var borderPrimary: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue400) }
    public var borderPrimaryHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue700, darkModeColor: NeutralColors.blue300) }
    public var borderPrimaryActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue800, darkModeColor: NeutralColors.blue200) }
    public var borderPrimarySubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.blue300, darkModeColor: NeutralColors.blue700) }
    public var borderPrimarySubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue400, darkModeColor: NeutralColors.blue600) }
    public var borderPrimarySubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue500, darkModeColor: NeutralColors.blue500) }
    public var borderSecondary: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.white) }
    public var borderSecondaryHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray800, darkModeColor: NeutralColors.gray100) }
    public var borderSecondaryActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray700, darkModeColor: NeutralColors.gray200) }
    public var borderPositive: Color { Color.dynamicColor(defaultColor: NeutralColors.green600, darkModeColor: NeutralColors.green400) }
    public var borderPositiveHover: Color { Color.dynamicColor(defaultColor: NeutralColors.green700, darkModeColor: NeutralColors.green300) }
    public var borderPositiveActive: Color { Color.dynamicColor(defaultColor: NeutralColors.green800, darkModeColor: NeutralColors.green200) }
    public var borderPositiveSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.green300, darkModeColor: NeutralColors.green700) }
    public var borderPositiveSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.green400, darkModeColor: NeutralColors.green600) }
    public var borderPositiveSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.green500, darkModeColor: NeutralColors.green500) }
    public var borderNegative: Color { Color.dynamicColor(defaultColor: NeutralColors.red600, darkModeColor: NeutralColors.red400) }
    public var borderNegativeHover: Color { Color.dynamicColor(defaultColor: NeutralColors.red700, darkModeColor: NeutralColors.red300) }
    public var borderNegativeActive: Color { Color.dynamicColor(defaultColor: NeutralColors.red800, darkModeColor: NeutralColors.red200) }
    public var borderNegativeSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.red300, darkModeColor: NeutralColors.red700) }
    public var borderNegativeSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.red400, darkModeColor: NeutralColors.red600) }
    public var borderNegativeSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.red500, darkModeColor: NeutralColors.red500) }
    public var borderWarning: Color { Color.dynamicColor(defaultColor: NeutralColors.orange600, darkModeColor: NeutralColors.orange500) }
    public var borderWarningHover: Color { Color.dynamicColor(defaultColor: NeutralColors.orange700, darkModeColor: NeutralColors.orange400) }
    public var borderWarningActive: Color { Color.dynamicColor(defaultColor: NeutralColors.orange800, darkModeColor: NeutralColors.orange300) }
    public var borderWarningSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.orange300, darkModeColor: NeutralColors.orange700) }
    public var borderWarningSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.orange400, darkModeColor: NeutralColors.orange600) }
    public var borderWarningSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.orange500, darkModeColor: NeutralColors.orange500) }
    public var borderInfo: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue500) }
    public var borderInfoHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue700, darkModeColor: NeutralColors.blue400) }
    public var borderInfoActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue800, darkModeColor: NeutralColors.blue300) }
    public var borderInfoSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.blue300, darkModeColor: NeutralColors.blue700) }
    public var borderInfoSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue400, darkModeColor: NeutralColors.blue600) }
    public var borderInfoSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue500, darkModeColor: NeutralColors.blue500) }
    public var borderFocus: Color { Color.dynamicColor(defaultColor: NeutralColors.blue400, darkModeColor: NeutralColors.blue300) }
    public var icon: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.white) }
    public var iconHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue700, darkModeColor: NeutralColors.blue100) }
    public var iconActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue800, darkModeColor: NeutralColors.blue200) }
    public var iconStatic: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.gray900) }
    public var iconSelected: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue400) }
    public var iconSelectedHover: Color { Color.dynamicColor(defaultColor: NeutralColors.blue700, darkModeColor: NeutralColors.blue300) }
    public var iconSelectedActive: Color { Color.dynamicColor(defaultColor: NeutralColors.blue800, darkModeColor: NeutralColors.blue200) }
    public var iconDisabled: Color { Color.dynamicColor(defaultColor: NeutralColors.gray300, darkModeColor: NeutralColors.gray600) }
    public var iconSubtle: Color { Color.dynamicColor(defaultColor: NeutralColors.gray600, darkModeColor: NeutralColors.gray400) }
    public var iconSubtleHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray700, darkModeColor: NeutralColors.gray300) }
    public var iconSubtleActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray800, darkModeColor: NeutralColors.gray200) }
    public var iconInverted: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.gray900) }
    public var iconInvertedHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray100, darkModeColor: NeutralColors.gray850) }
    public var iconInvertedActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray200, darkModeColor: NeutralColors.gray800) }
    public var iconInvertedStatic: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.white) }
    public var iconPrimary: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue400) }
    public var iconSecondary: Color { Color.dynamicColor(defaultColor: NeutralColors.gray900, darkModeColor: NeutralColors.white) }
    public var iconSecondaryHover: Color { Color.dynamicColor(defaultColor: NeutralColors.gray800, darkModeColor: NeutralColors.gray100) }
    public var iconSecondaryActive: Color { Color.dynamicColor(defaultColor: NeutralColors.gray700, darkModeColor: NeutralColors.gray200) }
    public var iconPositive: Color { Color.dynamicColor(defaultColor: NeutralColors.green600, darkModeColor: NeutralColors.green400) }
    public var iconNegative: Color { Color.dynamicColor(defaultColor: NeutralColors.red600, darkModeColor: NeutralColors.red400) }
    public var iconWarning: Color { Color.dynamicColor(defaultColor: NeutralColors.orange600, darkModeColor: NeutralColors.orange500) }
    public var iconInfo: Color { Color.dynamicColor(defaultColor: NeutralColors.blue600, darkModeColor: NeutralColors.blue500) }
    public var iconNotification: Color { Color.dynamicColor(defaultColor: NeutralColors.white, darkModeColor: NeutralColors.white) }
}

struct NeutralUITokenProvider: UITokenProvider {
    public var text: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.white) }
    public var textSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray600, darkModeColor: NeutralUIColors.gray400) }
    public var textStatic: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.gray900) }
    public var textPlaceholder: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray300, darkModeColor: NeutralUIColors.gray500) }
    public var textInverted: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.gray900) }
    public var textInvertedSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray400, darkModeColor: NeutralUIColors.gray600) }
    public var textInvertedStatic: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.white) }
    public var textLink: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue400) }
    public var textDisabled: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray300, darkModeColor: NeutralUIColors.gray500) }
    public var textNegative: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red600, darkModeColor: NeutralUIColors.red400) }
    public var textPositive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green600, darkModeColor: NeutralUIColors.green400) }
    public var background: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.gray900) }
    public var backgroundHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray100, darkModeColor: NeutralUIColors.gray850) }
    public var backgroundActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray200, darkModeColor: NeutralUIColors.gray800) }
    public var backgroundSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray100, darkModeColor: NeutralUIColors.gray750) }
    public var backgroundSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray200, darkModeColor: NeutralUIColors.gray700) }
    public var backgroundSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray300, darkModeColor: NeutralUIColors.gray600) }
    public var backgroundDisabled: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray300, darkModeColor: NeutralUIColors.gray700) }
    public var backgroundDisabledSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray200, darkModeColor: NeutralUIColors.gray600) }
    public var backgroundSelected: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue50, darkModeColor: NeutralUIColors.blue900) }
    public var backgroundSelectedHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue100, darkModeColor: NeutralUIColors.blue800) }
    public var backgroundSelectedActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue200, darkModeColor: NeutralUIColors.blue700) }
    public var backgroundInverted: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.gray50) }
    public var backgroundPrimary: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue400) }
    public var backgroundPrimaryHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue700, darkModeColor: NeutralUIColors.blue300) }
    public var backgroundPrimaryActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue800, darkModeColor: NeutralUIColors.blue200) }
    public var backgroundPrimarySubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue100, darkModeColor: NeutralUIColors.blue850) }
    public var backgroundPrimarySubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue200, darkModeColor: NeutralUIColors.blue800) }
    public var backgroundPrimarySubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue300, darkModeColor: NeutralUIColors.blue750) }
    public var backgroundSecondary: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.white) }
    public var backgroundSecondaryHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray800, darkModeColor: NeutralUIColors.gray100) }
    public var backgroundSecondaryActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray700, darkModeColor: NeutralUIColors.gray200) }
    public var backgroundPositive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green600, darkModeColor: NeutralUIColors.green400) }
    public var backgroundPositiveHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green700, darkModeColor: NeutralUIColors.green300) }
    public var backgroundPositiveActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green800, darkModeColor: NeutralUIColors.green200) }
    public var backgroundPositiveSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green50, darkModeColor: NeutralUIColors.green900) }
    public var backgroundPositiveSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green100, darkModeColor: NeutralUIColors.green800) }
    public var backgroundPositiveSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green200, darkModeColor: NeutralUIColors.green700) }
    public var backgroundNegative: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red600, darkModeColor: NeutralUIColors.red400) }
    public var backgroundNegativeHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red700, darkModeColor: NeutralUIColors.red300) }
    public var backgroundNegativeActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red800, darkModeColor: NeutralUIColors.red200) }
    public var backgroundNegativeSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red50, darkModeColor: NeutralUIColors.red900) }
    public var backgroundNegativeSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red100, darkModeColor: NeutralUIColors.red800) }
    public var backgroundNegativeSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red200, darkModeColor: NeutralUIColors.red700) }
    public var backgroundWarning: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange600, darkModeColor: NeutralUIColors.orange500) }
    public var backgroundWarningHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange700, darkModeColor: NeutralUIColors.orange400) }
    public var backgroundWarningActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange800, darkModeColor: NeutralUIColors.orange300) }
    public var backgroundWarningSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange50, darkModeColor: NeutralUIColors.orange900) }
    public var backgroundWarningSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange100, darkModeColor: NeutralUIColors.orange800) }
    public var backgroundWarningSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange200, darkModeColor: NeutralUIColors.orange700) }
    public var backgroundInfo: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue500) }
    public var backgroundInfoHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue700, darkModeColor: NeutralUIColors.blue400) }
    public var backgroundInfoActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue800, darkModeColor: NeutralUIColors.blue300) }
    public var backgroundInfoSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue50, darkModeColor: NeutralUIColors.blue900) }
    public var backgroundInfoSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue100, darkModeColor: NeutralUIColors.blue800) }
    public var backgroundInfoSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue200, darkModeColor: NeutralUIColors.blue700) }
    public var backgroundTransparent0: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.transparent, darkModeColor: NeutralUIColors.transparent) }
    public var backgroundNotification: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red600, darkModeColor: NeutralUIColors.red500) }
    public var surfaceSunken: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray50, darkModeColor: NeutralUIColors.gray950) }
    public var surfaceElevated100: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.gray850) }
    public var surfaceElevated100Hover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray100, darkModeColor: NeutralUIColors.gray800) }
    public var surfaceElevated100Active: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray200, darkModeColor: NeutralUIColors.gray750) }
    public var surfaceElevated200: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.gray800) }
    public var surfaceElevated200Hover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray100, darkModeColor: NeutralUIColors.gray750) }
    public var surfaceElevated200Active: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray200, darkModeColor: NeutralUIColors.gray700) }
    public var surfaceElevated300: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.gray750) }
    public var surfaceElevated300Hover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray100, darkModeColor: NeutralUIColors.gray700) }
    public var surfaceElevated300Active: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray200, darkModeColor: NeutralUIColors.gray600) }
    public var border: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray300, darkModeColor: NeutralUIColors.gray600) }
    public var borderHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray400, darkModeColor: NeutralUIColors.gray500) }
    public var borderActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray500, darkModeColor: NeutralUIColors.gray400) }
    public var borderDisabled: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray300, darkModeColor: NeutralUIColors.gray700) }
    public var borderSelected: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue400) }
    public var borderSelectedHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue700, darkModeColor: NeutralUIColors.blue300) }
    public var borderSelectedActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue800, darkModeColor: NeutralUIColors.blue200) }
    public var borderInverted: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.gray900) }
    public var borderPrimary: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue400) }
    public var borderPrimaryHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue700, darkModeColor: NeutralUIColors.blue300) }
    public var borderPrimaryActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue800, darkModeColor: NeutralUIColors.blue200) }
    public var borderPrimarySubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue300, darkModeColor: NeutralUIColors.blue700) }
    public var borderPrimarySubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue400, darkModeColor: NeutralUIColors.blue600) }
    public var borderPrimarySubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue500, darkModeColor: NeutralUIColors.blue500) }
    public var borderSecondary: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.white) }
    public var borderSecondaryHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray800, darkModeColor: NeutralUIColors.gray100) }
    public var borderSecondaryActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray700, darkModeColor: NeutralUIColors.gray200) }
    public var borderPositive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green600, darkModeColor: NeutralUIColors.green400) }
    public var borderPositiveHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green700, darkModeColor: NeutralUIColors.green300) }
    public var borderPositiveActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green800, darkModeColor: NeutralUIColors.green200) }
    public var borderPositiveSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green300, darkModeColor: NeutralUIColors.green700) }
    public var borderPositiveSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green400, darkModeColor: NeutralUIColors.green600) }
    public var borderPositiveSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green500, darkModeColor: NeutralUIColors.green500) }
    public var borderNegative: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red600, darkModeColor: NeutralUIColors.red400) }
    public var borderNegativeHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red700, darkModeColor: NeutralUIColors.red300) }
    public var borderNegativeActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red800, darkModeColor: NeutralUIColors.red200) }
    public var borderNegativeSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red300, darkModeColor: NeutralUIColors.red700) }
    public var borderNegativeSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red400, darkModeColor: NeutralUIColors.red600) }
    public var borderNegativeSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red500, darkModeColor: NeutralUIColors.red500) }
    public var borderWarning: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange600, darkModeColor: NeutralUIColors.orange500) }
    public var borderWarningHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange700, darkModeColor: NeutralUIColors.orange400) }
    public var borderWarningActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange800, darkModeColor: NeutralUIColors.orange300) }
    public var borderWarningSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange300, darkModeColor: NeutralUIColors.orange700) }
    public var borderWarningSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange400, darkModeColor: NeutralUIColors.orange600) }
    public var borderWarningSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange500, darkModeColor: NeutralUIColors.orange500) }
    public var borderInfo: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue500) }
    public var borderInfoHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue700, darkModeColor: NeutralUIColors.blue400) }
    public var borderInfoActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue800, darkModeColor: NeutralUIColors.blue300) }
    public var borderInfoSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue300, darkModeColor: NeutralUIColors.blue700) }
    public var borderInfoSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue400, darkModeColor: NeutralUIColors.blue600) }
    public var borderInfoSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue500, darkModeColor: NeutralUIColors.blue500) }
    public var borderFocus: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue400, darkModeColor: NeutralUIColors.blue300) }
    public var icon: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.white) }
    public var iconHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue700, darkModeColor: NeutralUIColors.blue100) }
    public var iconActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue800, darkModeColor: NeutralUIColors.blue200) }
    public var iconStatic: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.gray900) }
    public var iconSelected: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue400) }
    public var iconSelectedHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue700, darkModeColor: NeutralUIColors.blue300) }
    public var iconSelectedActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue800, darkModeColor: NeutralUIColors.blue200) }
    public var iconDisabled: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray300, darkModeColor: NeutralUIColors.gray600) }
    public var iconSubtle: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray600, darkModeColor: NeutralUIColors.gray400) }
    public var iconSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray700, darkModeColor: NeutralUIColors.gray300) }
    public var iconSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray800, darkModeColor: NeutralUIColors.gray200) }
    public var iconInverted: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.gray900) }
    public var iconInvertedHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray100, darkModeColor: NeutralUIColors.gray850) }
    public var iconInvertedActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray200, darkModeColor: NeutralUIColors.gray800) }
    public var iconInvertedStatic: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.white) }
    public var iconPrimary: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue400) }
    public var iconSecondary: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray900, darkModeColor: NeutralUIColors.white) }
    public var iconSecondaryHover: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray800, darkModeColor: NeutralUIColors.gray100) }
    public var iconSecondaryActive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.gray700, darkModeColor: NeutralUIColors.gray200) }
    public var iconPositive: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.green600, darkModeColor: NeutralUIColors.green400) }
    public var iconNegative: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.red600, darkModeColor: NeutralUIColors.red400) }
    public var iconWarning: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.orange600, darkModeColor: NeutralUIColors.orange500) }
    public var iconInfo: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.blue600, darkModeColor: NeutralUIColors.blue500) }
    public var iconNotification: UIColor { UIColor.dynamicColor(defaultColor: NeutralUIColors.white, darkModeColor: NeutralUIColors.white) }
}
