import SwiftUI

// Generated on Wed, 01 Oct 2025 07:49:52 GMT by https://github.com/warp-ds/tokens
struct VendTokenProvider: TokenProvider {
    public var text: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var textSubtle: Color { Color.dynamicColor(defaultColor: VendColors.gray600, darkModeColor: VendColors.gray400) }
    public var textStatic: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.gray900) }
    public var textPlaceholder: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray500) }
    public var textInverted: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.gray900) }
    public var textInvertedSubtle: Color { Color.dynamicColor(defaultColor: VendColors.gray400, darkModeColor: VendColors.gray600) }
    public var textInvertedStatic: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.white) }
    public var textLink: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var textDisabled: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray500) }
    public var textNegative: Color { Color.dynamicColor(defaultColor: VendColors.red600, darkModeColor: VendColors.red400) }
    public var textPositive: Color { Color.dynamicColor(defaultColor: VendColors.green600, darkModeColor: VendColors.green400) }
    public var icon: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var iconHover: Color { Color.dynamicColor(defaultColor: VendColors.gray800, darkModeColor: VendColors.gray100) }
    public var iconActive: Color { Color.dynamicColor(defaultColor: VendColors.gray700, darkModeColor: VendColors.gray200) }
    public var iconStatic: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.gray900) }
    public var iconSelected: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var iconSelectedHover: Color { Color.dynamicColor(defaultColor: VendColors.gray800, darkModeColor: VendColors.gray100) }
    public var iconSelectedActive: Color { Color.dynamicColor(defaultColor: VendColors.gray700, darkModeColor: VendColors.gray200) }
    public var iconDisabled: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray600) }
    public var iconSubtle: Color { Color.dynamicColor(defaultColor: VendColors.gray600, darkModeColor: VendColors.gray400) }
    public var iconSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.gray700, darkModeColor: VendColors.gray300) }
    public var iconSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.gray800, darkModeColor: VendColors.gray200) }
    public var iconInverted: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.gray900) }
    public var iconInvertedHover: Color { Color.dynamicColor(defaultColor: VendColors.gray100, darkModeColor: VendColors.gray850) }
    public var iconInvertedActive: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray800) }
    public var iconInvertedStatic: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.white) }
    public var iconPrimary: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var iconSecondary: Color { Color.dynamicColor(defaultColor: VendColors.brown600, darkModeColor: VendColors.brown400) }
    public var iconSecondaryHover: Color { Color.dynamicColor(defaultColor: VendColors.brown700, darkModeColor: VendColors.brown300) }
    public var iconSecondaryActive: Color { Color.dynamicColor(defaultColor: VendColors.brown800, darkModeColor: VendColors.brown200) }
    public var iconPositive: Color { Color.dynamicColor(defaultColor: VendColors.green600, darkModeColor: VendColors.green400) }
    public var iconNegative: Color { Color.dynamicColor(defaultColor: VendColors.red600, darkModeColor: VendColors.red400) }
    public var iconWarning: Color { Color.dynamicColor(defaultColor: VendColors.orange600, darkModeColor: VendColors.orange500) }
    public var iconInfo: Color { Color.dynamicColor(defaultColor: VendColors.blue600, darkModeColor: VendColors.blue500) }
    public var iconNotification: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.white) }
    public var background: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.gray900) }
    public var backgroundHover: Color { Color.dynamicColor(defaultColor: VendColors.gray100, darkModeColor: VendColors.gray850) }
    public var backgroundActive: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray800) }
    public var backgroundSubtle: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray750) }
    public var backgroundSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray700) }
    public var backgroundSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.gray400, darkModeColor: VendColors.gray600) }
    public var backgroundDisabled: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray700) }
    public var backgroundDisabledSubtle: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray600) }
    public var backgroundSelected: Color { Color.dynamicColor(defaultColor: VendColors.gray50, darkModeColor: VendColors.gray900) }
    public var backgroundSelectedHover: Color { Color.dynamicColor(defaultColor: VendColors.gray100, darkModeColor: VendColors.gray800) }
    public var backgroundSelectedActive: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray700) }
    public var backgroundInverted: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.gray50) }
    public var backgroundPrimary: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var backgroundPrimaryHover: Color { Color.dynamicColor(defaultColor: VendColors.gray800, darkModeColor: VendColors.gray100) }
    public var backgroundPrimaryActive: Color { Color.dynamicColor(defaultColor: VendColors.gray700, darkModeColor: VendColors.gray200) }
    public var backgroundPrimarySubtle: Color { Color.dynamicColor(defaultColor: VendColors.gray100, darkModeColor: VendColors.gray850) }
    public var backgroundPrimarySubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray800) }
    public var backgroundPrimarySubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray750) }
    public var backgroundSecondary: Color { Color.dynamicColor(defaultColor: VendColors.brown600, darkModeColor: VendColors.brown400) }
    public var backgroundSecondaryHover: Color { Color.dynamicColor(defaultColor: VendColors.brown700, darkModeColor: VendColors.brown300) }
    public var backgroundSecondaryActive: Color { Color.dynamicColor(defaultColor: VendColors.brown800, darkModeColor: VendColors.brown200) }
    public var backgroundPositive: Color { Color.dynamicColor(defaultColor: VendColors.green600, darkModeColor: VendColors.green400) }
    public var backgroundPositiveHover: Color { Color.dynamicColor(defaultColor: VendColors.green700, darkModeColor: VendColors.green300) }
    public var backgroundPositiveActive: Color { Color.dynamicColor(defaultColor: VendColors.green800, darkModeColor: VendColors.green200) }
    public var backgroundPositiveSubtle: Color { Color.dynamicColor(defaultColor: VendColors.green50, darkModeColor: VendColors.green900) }
    public var backgroundPositiveSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.green100, darkModeColor: VendColors.green800) }
    public var backgroundPositiveSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.green200, darkModeColor: VendColors.green700) }
    public var backgroundNegative: Color { Color.dynamicColor(defaultColor: VendColors.red600, darkModeColor: VendColors.red400) }
    public var backgroundNegativeHover: Color { Color.dynamicColor(defaultColor: VendColors.red700, darkModeColor: VendColors.red300) }
    public var backgroundNegativeActive: Color { Color.dynamicColor(defaultColor: VendColors.red800, darkModeColor: VendColors.red200) }
    public var backgroundNegativeSubtle: Color { Color.dynamicColor(defaultColor: VendColors.red50, darkModeColor: VendColors.red900) }
    public var backgroundNegativeSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.red100, darkModeColor: VendColors.red800) }
    public var backgroundNegativeSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.red200, darkModeColor: VendColors.red700) }
    public var backgroundWarning: Color { Color.dynamicColor(defaultColor: VendColors.orange600, darkModeColor: VendColors.orange500) }
    public var backgroundWarningHover: Color { Color.dynamicColor(defaultColor: VendColors.orange700, darkModeColor: VendColors.orange400) }
    public var backgroundWarningActive: Color { Color.dynamicColor(defaultColor: VendColors.orange800, darkModeColor: VendColors.orange300) }
    public var backgroundWarningSubtle: Color { Color.dynamicColor(defaultColor: VendColors.orange50, darkModeColor: VendColors.orange900) }
    public var backgroundWarningSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.orange100, darkModeColor: VendColors.orange800) }
    public var backgroundWarningSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.orange200, darkModeColor: VendColors.orange700) }
    public var backgroundInfo: Color { Color.dynamicColor(defaultColor: VendColors.blue600, darkModeColor: VendColors.blue500) }
    public var backgroundInfoHover: Color { Color.dynamicColor(defaultColor: VendColors.blue700, darkModeColor: VendColors.blue400) }
    public var backgroundInfoActive: Color { Color.dynamicColor(defaultColor: VendColors.blue800, darkModeColor: VendColors.blue300) }
    public var backgroundInfoSubtle: Color { Color.dynamicColor(defaultColor: VendColors.blue50, darkModeColor: VendColors.blue900) }
    public var backgroundInfoSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.blue100, darkModeColor: VendColors.blue800) }
    public var backgroundInfoSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.blue200, darkModeColor: VendColors.blue700) }
    public var backgroundTransparent0: Color { Color.dynamicColor(defaultColor: VendColors.transparent, darkModeColor: VendColors.transparent) }
    public var backgroundNotification: Color { Color.dynamicColor(defaultColor: VendColors.red600, darkModeColor: VendColors.red500) }
    public var surfaceSunken: Color { Color.dynamicColor(defaultColor: VendColors.gray50, darkModeColor: VendColors.gray950) }
    public var surfaceElevated100: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.gray850) }
    public var surfaceElevated100Hover: Color { Color.dynamicColor(defaultColor: VendColors.gray100, darkModeColor: VendColors.gray800) }
    public var surfaceElevated100Active: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray750) }
    public var surfaceElevated200: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.gray800) }
    public var surfaceElevated200Hover: Color { Color.dynamicColor(defaultColor: VendColors.gray100, darkModeColor: VendColors.gray750) }
    public var surfaceElevated200Active: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray700) }
    public var surfaceElevated300: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.gray750) }
    public var surfaceElevated300Hover: Color { Color.dynamicColor(defaultColor: VendColors.gray100, darkModeColor: VendColors.gray700) }
    public var surfaceElevated300Active: Color { Color.dynamicColor(defaultColor: VendColors.gray200, darkModeColor: VendColors.gray600) }
    public var border: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray600) }
    public var borderHover: Color { Color.dynamicColor(defaultColor: VendColors.gray400, darkModeColor: VendColors.gray500) }
    public var borderActive: Color { Color.dynamicColor(defaultColor: VendColors.gray500, darkModeColor: VendColors.gray400) }
    public var borderStrong: Color { Color.dynamicColor(defaultColor: VendColors.gray500, darkModeColor: VendColors.gray500) }
    public var borderStrongHover: Color { Color.dynamicColor(defaultColor: VendColors.gray600, darkModeColor: VendColors.gray400) }
    public var borderDisabled: Color { Color.dynamicColor(defaultColor: VendColors.gray300, darkModeColor: VendColors.gray700) }
    public var borderSelected: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var borderSelectedHover: Color { Color.dynamicColor(defaultColor: VendColors.gray800, darkModeColor: VendColors.gray100) }
    public var borderSelectedActive: Color { Color.dynamicColor(defaultColor: VendColors.gray700, darkModeColor: VendColors.gray200) }
    public var borderInverted: Color { Color.dynamicColor(defaultColor: VendColors.white, darkModeColor: VendColors.gray900) }
    public var borderPrimary: Color { Color.dynamicColor(defaultColor: VendColors.gray900, darkModeColor: VendColors.white) }
    public var borderPrimaryHover: Color { Color.dynamicColor(defaultColor: VendColors.gray800, darkModeColor: VendColors.gray100) }
    public var borderPrimaryActive: Color { Color.dynamicColor(defaultColor: VendColors.gray700, darkModeColor: VendColors.gray200) }
    public var borderPrimarySubtle: Color { Color.dynamicColor(defaultColor: VendColors.gray400, darkModeColor: VendColors.gray700) }
    public var borderPrimarySubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.gray500, darkModeColor: VendColors.gray600) }
    public var borderPrimarySubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.gray600, darkModeColor: VendColors.gray500) }
    public var borderSecondary: Color { Color.dynamicColor(defaultColor: VendColors.brown600, darkModeColor: VendColors.brown400) }
    public var borderSecondaryHover: Color { Color.dynamicColor(defaultColor: VendColors.brown700, darkModeColor: VendColors.brown300) }
    public var borderSecondaryActive: Color { Color.dynamicColor(defaultColor: VendColors.brown800, darkModeColor: VendColors.brown200) }
    public var borderPositive: Color { Color.dynamicColor(defaultColor: VendColors.green600, darkModeColor: VendColors.green400) }
    public var borderPositiveHover: Color { Color.dynamicColor(defaultColor: VendColors.green700, darkModeColor: VendColors.green300) }
    public var borderPositiveActive: Color { Color.dynamicColor(defaultColor: VendColors.green800, darkModeColor: VendColors.green200) }
    public var borderPositiveSubtle: Color { Color.dynamicColor(defaultColor: VendColors.green300, darkModeColor: VendColors.green700) }
    public var borderPositiveSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.green400, darkModeColor: VendColors.green600) }
    public var borderPositiveSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.green500, darkModeColor: VendColors.green500) }
    public var borderNegative: Color { Color.dynamicColor(defaultColor: VendColors.red600, darkModeColor: VendColors.red400) }
    public var borderNegativeHover: Color { Color.dynamicColor(defaultColor: VendColors.red700, darkModeColor: VendColors.red300) }
    public var borderNegativeActive: Color { Color.dynamicColor(defaultColor: VendColors.red800, darkModeColor: VendColors.red200) }
    public var borderNegativeSubtle: Color { Color.dynamicColor(defaultColor: VendColors.red300, darkModeColor: VendColors.red700) }
    public var borderNegativeSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.red400, darkModeColor: VendColors.red600) }
    public var borderNegativeSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.red500, darkModeColor: VendColors.red500) }
    public var borderWarning: Color { Color.dynamicColor(defaultColor: VendColors.orange600, darkModeColor: VendColors.orange500) }
    public var borderWarningHover: Color { Color.dynamicColor(defaultColor: VendColors.orange700, darkModeColor: VendColors.orange400) }
    public var borderWarningActive: Color { Color.dynamicColor(defaultColor: VendColors.orange800, darkModeColor: VendColors.orange300) }
    public var borderWarningSubtle: Color { Color.dynamicColor(defaultColor: VendColors.orange300, darkModeColor: VendColors.orange700) }
    public var borderWarningSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.orange400, darkModeColor: VendColors.orange600) }
    public var borderWarningSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.orange500, darkModeColor: VendColors.orange500) }
    public var borderInfo: Color { Color.dynamicColor(defaultColor: VendColors.blue600, darkModeColor: VendColors.blue500) }
    public var borderInfoHover: Color { Color.dynamicColor(defaultColor: VendColors.blue700, darkModeColor: VendColors.blue400) }
    public var borderInfoActive: Color { Color.dynamicColor(defaultColor: VendColors.blue800, darkModeColor: VendColors.blue300) }
    public var borderInfoSubtle: Color { Color.dynamicColor(defaultColor: VendColors.blue300, darkModeColor: VendColors.blue700) }
    public var borderInfoSubtleHover: Color { Color.dynamicColor(defaultColor: VendColors.blue400, darkModeColor: VendColors.blue600) }
    public var borderInfoSubtleActive: Color { Color.dynamicColor(defaultColor: VendColors.blue500, darkModeColor: VendColors.blue500) }
    public var borderFocus: Color { Color.dynamicColor(defaultColor: VendColors.blue400, darkModeColor: VendColors.blue300) }
}

struct VendUITokenProvider: UITokenProvider {
    public var text: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var textSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray600, darkModeColor: VendUIColors.gray400) }
    public var textStatic: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.gray900) }
    public var textPlaceholder: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray500) }
    public var textInverted: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.gray900) }
    public var textInvertedSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray400, darkModeColor: VendUIColors.gray600) }
    public var textInvertedStatic: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.white) }
    public var textLink: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var textDisabled: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray500) }
    public var textNegative: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red600, darkModeColor: VendUIColors.red400) }
    public var textPositive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green600, darkModeColor: VendUIColors.green400) }
    public var icon: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var iconHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray800, darkModeColor: VendUIColors.gray100) }
    public var iconActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray700, darkModeColor: VendUIColors.gray200) }
    public var iconStatic: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.gray900) }
    public var iconSelected: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var iconSelectedHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray800, darkModeColor: VendUIColors.gray100) }
    public var iconSelectedActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray700, darkModeColor: VendUIColors.gray200) }
    public var iconDisabled: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray600) }
    public var iconSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray600, darkModeColor: VendUIColors.gray400) }
    public var iconSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray700, darkModeColor: VendUIColors.gray300) }
    public var iconSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray800, darkModeColor: VendUIColors.gray200) }
    public var iconInverted: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.gray900) }
    public var iconInvertedHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray100, darkModeColor: VendUIColors.gray850) }
    public var iconInvertedActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray800) }
    public var iconInvertedStatic: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.white) }
    public var iconPrimary: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var iconSecondary: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown600, darkModeColor: VendUIColors.brown400) }
    public var iconSecondaryHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown700, darkModeColor: VendUIColors.brown300) }
    public var iconSecondaryActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown800, darkModeColor: VendUIColors.brown200) }
    public var iconPositive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green600, darkModeColor: VendUIColors.green400) }
    public var iconNegative: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red600, darkModeColor: VendUIColors.red400) }
    public var iconWarning: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange600, darkModeColor: VendUIColors.orange500) }
    public var iconInfo: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue600, darkModeColor: VendUIColors.blue500) }
    public var iconNotification: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.white) }
    public var background: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.gray900) }
    public var backgroundHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray100, darkModeColor: VendUIColors.gray850) }
    public var backgroundActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray800) }
    public var backgroundSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray750) }
    public var backgroundSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray700) }
    public var backgroundSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray400, darkModeColor: VendUIColors.gray600) }
    public var backgroundDisabled: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray700) }
    public var backgroundDisabledSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray600) }
    public var backgroundSelected: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray50, darkModeColor: VendUIColors.gray900) }
    public var backgroundSelectedHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray100, darkModeColor: VendUIColors.gray800) }
    public var backgroundSelectedActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray700) }
    public var backgroundInverted: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.gray50) }
    public var backgroundPrimary: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var backgroundPrimaryHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray800, darkModeColor: VendUIColors.gray100) }
    public var backgroundPrimaryActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray700, darkModeColor: VendUIColors.gray200) }
    public var backgroundPrimarySubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray100, darkModeColor: VendUIColors.gray850) }
    public var backgroundPrimarySubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray800) }
    public var backgroundPrimarySubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray750) }
    public var backgroundSecondary: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown600, darkModeColor: VendUIColors.brown400) }
    public var backgroundSecondaryHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown700, darkModeColor: VendUIColors.brown300) }
    public var backgroundSecondaryActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown800, darkModeColor: VendUIColors.brown200) }
    public var backgroundPositive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green600, darkModeColor: VendUIColors.green400) }
    public var backgroundPositiveHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green700, darkModeColor: VendUIColors.green300) }
    public var backgroundPositiveActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green800, darkModeColor: VendUIColors.green200) }
    public var backgroundPositiveSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green50, darkModeColor: VendUIColors.green900) }
    public var backgroundPositiveSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green100, darkModeColor: VendUIColors.green800) }
    public var backgroundPositiveSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green200, darkModeColor: VendUIColors.green700) }
    public var backgroundNegative: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red600, darkModeColor: VendUIColors.red400) }
    public var backgroundNegativeHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red700, darkModeColor: VendUIColors.red300) }
    public var backgroundNegativeActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red800, darkModeColor: VendUIColors.red200) }
    public var backgroundNegativeSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red50, darkModeColor: VendUIColors.red900) }
    public var backgroundNegativeSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red100, darkModeColor: VendUIColors.red800) }
    public var backgroundNegativeSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red200, darkModeColor: VendUIColors.red700) }
    public var backgroundWarning: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange600, darkModeColor: VendUIColors.orange500) }
    public var backgroundWarningHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange700, darkModeColor: VendUIColors.orange400) }
    public var backgroundWarningActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange800, darkModeColor: VendUIColors.orange300) }
    public var backgroundWarningSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange50, darkModeColor: VendUIColors.orange900) }
    public var backgroundWarningSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange100, darkModeColor: VendUIColors.orange800) }
    public var backgroundWarningSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange200, darkModeColor: VendUIColors.orange700) }
    public var backgroundInfo: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue600, darkModeColor: VendUIColors.blue500) }
    public var backgroundInfoHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue700, darkModeColor: VendUIColors.blue400) }
    public var backgroundInfoActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue800, darkModeColor: VendUIColors.blue300) }
    public var backgroundInfoSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue50, darkModeColor: VendUIColors.blue900) }
    public var backgroundInfoSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue100, darkModeColor: VendUIColors.blue800) }
    public var backgroundInfoSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue200, darkModeColor: VendUIColors.blue700) }
    public var backgroundTransparent0: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.transparent, darkModeColor: VendUIColors.transparent) }
    public var backgroundNotification: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red600, darkModeColor: VendUIColors.red500) }
    public var surfaceSunken: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray50, darkModeColor: VendUIColors.gray950) }
    public var surfaceElevated100: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.gray850) }
    public var surfaceElevated100Hover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray100, darkModeColor: VendUIColors.gray800) }
    public var surfaceElevated100Active: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray750) }
    public var surfaceElevated200: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.gray800) }
    public var surfaceElevated200Hover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray100, darkModeColor: VendUIColors.gray750) }
    public var surfaceElevated200Active: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray700) }
    public var surfaceElevated300: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.gray750) }
    public var surfaceElevated300Hover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray100, darkModeColor: VendUIColors.gray700) }
    public var surfaceElevated300Active: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray200, darkModeColor: VendUIColors.gray600) }
    public var border: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray600) }
    public var borderHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray400, darkModeColor: VendUIColors.gray500) }
    public var borderActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray500, darkModeColor: VendUIColors.gray400) }
    public var borderStrong: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray500, darkModeColor: VendUIColors.gray500) }
    public var borderStrongHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray600, darkModeColor: VendUIColors.gray400) }
    public var borderDisabled: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray300, darkModeColor: VendUIColors.gray700) }
    public var borderSelected: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var borderSelectedHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray800, darkModeColor: VendUIColors.gray100) }
    public var borderSelectedActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray700, darkModeColor: VendUIColors.gray200) }
    public var borderInverted: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.white, darkModeColor: VendUIColors.gray900) }
    public var borderPrimary: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray900, darkModeColor: VendUIColors.white) }
    public var borderPrimaryHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray800, darkModeColor: VendUIColors.gray100) }
    public var borderPrimaryActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray700, darkModeColor: VendUIColors.gray200) }
    public var borderPrimarySubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray400, darkModeColor: VendUIColors.gray700) }
    public var borderPrimarySubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray500, darkModeColor: VendUIColors.gray600) }
    public var borderPrimarySubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.gray600, darkModeColor: VendUIColors.gray500) }
    public var borderSecondary: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown600, darkModeColor: VendUIColors.brown400) }
    public var borderSecondaryHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown700, darkModeColor: VendUIColors.brown300) }
    public var borderSecondaryActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.brown800, darkModeColor: VendUIColors.brown200) }
    public var borderPositive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green600, darkModeColor: VendUIColors.green400) }
    public var borderPositiveHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green700, darkModeColor: VendUIColors.green300) }
    public var borderPositiveActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green800, darkModeColor: VendUIColors.green200) }
    public var borderPositiveSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green300, darkModeColor: VendUIColors.green700) }
    public var borderPositiveSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green400, darkModeColor: VendUIColors.green600) }
    public var borderPositiveSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.green500, darkModeColor: VendUIColors.green500) }
    public var borderNegative: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red600, darkModeColor: VendUIColors.red400) }
    public var borderNegativeHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red700, darkModeColor: VendUIColors.red300) }
    public var borderNegativeActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red800, darkModeColor: VendUIColors.red200) }
    public var borderNegativeSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red300, darkModeColor: VendUIColors.red700) }
    public var borderNegativeSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red400, darkModeColor: VendUIColors.red600) }
    public var borderNegativeSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.red500, darkModeColor: VendUIColors.red500) }
    public var borderWarning: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange600, darkModeColor: VendUIColors.orange500) }
    public var borderWarningHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange700, darkModeColor: VendUIColors.orange400) }
    public var borderWarningActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange800, darkModeColor: VendUIColors.orange300) }
    public var borderWarningSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange300, darkModeColor: VendUIColors.orange700) }
    public var borderWarningSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange400, darkModeColor: VendUIColors.orange600) }
    public var borderWarningSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.orange500, darkModeColor: VendUIColors.orange500) }
    public var borderInfo: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue600, darkModeColor: VendUIColors.blue500) }
    public var borderInfoHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue700, darkModeColor: VendUIColors.blue400) }
    public var borderInfoActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue800, darkModeColor: VendUIColors.blue300) }
    public var borderInfoSubtle: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue300, darkModeColor: VendUIColors.blue700) }
    public var borderInfoSubtleHover: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue400, darkModeColor: VendUIColors.blue600) }
    public var borderInfoSubtleActive: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue500, darkModeColor: VendUIColors.blue500) }
    public var borderFocus: UIColor { UIColor.dynamicColor(defaultColor: VendUIColors.blue400, darkModeColor: VendUIColors.blue300) }
}
