import SwiftUI

// Generated from TokenProvider.swift — do not edit by hand.
// Regenerate with Scripts/generate-color-variant.py

extension Warp.ColorVariant {
    /// A sparse set of token overrides.
    ///
    /// Every property defaults to `nil`, meaning "use the brand's value". A variant
    /// names only the tokens it changes; everything else falls through to the brand.
    struct Overrides: Sendable {
        var text: Color?
        var textSubtle: Color?
        var textStatic: Color?
        var textPlaceholder: Color?
        var textInverted: Color?
        var textInvertedSubtle: Color?
        var textInvertedStatic: Color?
        var textLink: Color?
        var textDisabled: Color?
        var textNegative: Color?
        var textPositive: Color?
        var icon: Color?
        var iconHover: Color?
        var iconActive: Color?
        var iconStatic: Color?
        var iconSelected: Color?
        var iconSelectedHover: Color?
        var iconSelectedActive: Color?
        var iconDisabled: Color?
        var iconSubtle: Color?
        var iconSubtleHover: Color?
        var iconSubtleActive: Color?
        var iconInverted: Color?
        var iconInvertedHover: Color?
        var iconInvertedActive: Color?
        var iconInvertedStatic: Color?
        var iconPrimary: Color?
        var iconSecondary: Color?
        var iconSecondaryHover: Color?
        var iconSecondaryActive: Color?
        var iconPositive: Color?
        var iconNegative: Color?
        var iconWarning: Color?
        var iconInfo: Color?
        var iconNotification: Color?
        var background: Color?
        var backgroundHover: Color?
        var backgroundActive: Color?
        var backgroundSubtle: Color?
        var backgroundSubtleHover: Color?
        var backgroundSubtleActive: Color?
        var backgroundDisabled: Color?
        var backgroundDisabledSubtle: Color?
        var backgroundSelected: Color?
        var backgroundSelectedHover: Color?
        var backgroundSelectedActive: Color?
        var backgroundInverted: Color?
        var backgroundPrimary: Color?
        var backgroundPrimaryHover: Color?
        var backgroundPrimaryActive: Color?
        var backgroundPrimarySubtle: Color?
        var backgroundPrimarySubtleHover: Color?
        var backgroundPrimarySubtleActive: Color?
        var backgroundSecondary: Color?
        var backgroundSecondaryHover: Color?
        var backgroundSecondaryActive: Color?
        var backgroundPositive: Color?
        var backgroundPositiveHover: Color?
        var backgroundPositiveActive: Color?
        var backgroundPositiveSubtle: Color?
        var backgroundPositiveSubtleHover: Color?
        var backgroundPositiveSubtleActive: Color?
        var backgroundNegative: Color?
        var backgroundNegativeHover: Color?
        var backgroundNegativeActive: Color?
        var backgroundNegativeSubtle: Color?
        var backgroundNegativeSubtleHover: Color?
        var backgroundNegativeSubtleActive: Color?
        var backgroundWarning: Color?
        var backgroundWarningHover: Color?
        var backgroundWarningActive: Color?
        var backgroundWarningSubtle: Color?
        var backgroundWarningSubtleHover: Color?
        var backgroundWarningSubtleActive: Color?
        var backgroundInfo: Color?
        var backgroundInfoHover: Color?
        var backgroundInfoActive: Color?
        var backgroundInfoSubtle: Color?
        var backgroundInfoSubtleHover: Color?
        var backgroundInfoSubtleActive: Color?
        var backgroundTransparent0: Color?
        var backgroundNotification: Color?
        var surfaceSunken: Color?
        var surfaceElevated100: Color?
        var surfaceElevated100Hover: Color?
        var surfaceElevated100Active: Color?
        var surfaceElevated200: Color?
        var surfaceElevated200Hover: Color?
        var surfaceElevated200Active: Color?
        var surfaceElevated300: Color?
        var surfaceElevated300Hover: Color?
        var surfaceElevated300Active: Color?
        var border: Color?
        var borderHover: Color?
        var borderActive: Color?
        var borderStrong: Color?
        var borderStrongHover: Color?
        var borderDisabled: Color?
        var borderSelected: Color?
        var borderSelectedHover: Color?
        var borderSelectedActive: Color?
        var borderInverted: Color?
        var borderPrimary: Color?
        var borderPrimaryHover: Color?
        var borderPrimaryActive: Color?
        var borderPrimarySubtle: Color?
        var borderPrimarySubtleHover: Color?
        var borderPrimarySubtleActive: Color?
        var borderSecondary: Color?
        var borderSecondaryHover: Color?
        var borderSecondaryActive: Color?
        var borderPositive: Color?
        var borderPositiveHover: Color?
        var borderPositiveActive: Color?
        var borderPositiveSubtle: Color?
        var borderPositiveSubtleHover: Color?
        var borderPositiveSubtleActive: Color?
        var borderNegative: Color?
        var borderNegativeHover: Color?
        var borderNegativeActive: Color?
        var borderNegativeSubtle: Color?
        var borderNegativeSubtleHover: Color?
        var borderNegativeSubtleActive: Color?
        var borderWarning: Color?
        var borderWarningHover: Color?
        var borderWarningActive: Color?
        var borderWarningSubtle: Color?
        var borderWarningSubtleHover: Color?
        var borderWarningSubtleActive: Color?
        var borderInfo: Color?
        var borderInfoHover: Color?
        var borderInfoActive: Color?
        var borderInfoSubtle: Color?
        var borderInfoSubtleHover: Color?
        var borderInfoSubtleActive: Color?
        var borderFocus: Color?

        init() {}
    }
}
