name: Crowdin Synchronisation

on:
  push:
    branches: [next]
  schedule:
    # We need a schedule to detect translations from Crowdin. Every 2nd hour from 8-17
    # on weekdays is a proposed starting point. You may change the minute counter to
    # avoid crashing with other workflows.
    - cron: "0 8-17/2 * * 1-5" # At minute 0 past every 2nd hour from 8 through 17 on every day-of-week from Monday through Friday (https://crontab.guru/#0_8-17/2_*_*_1-5)
  # Run a GitHub Action on demand, without having to push to next or wait for a scheduled run
  workflow_dispatch:
  # Forward comments in .po files from Crowdin PRs to the translator in Crowdin
  pull_request_review_comment:

jobs:
  synchronize-with-crowdin:
    uses: warp-ds/reusable-workflows/.github/workflows/crowdin-sync.yml@main
    secrets: inherit
    with:
      pull_request_reviewers: "mohsen-schibsted"